# -*- coding: utf-8 -*-
"""piae_final_v1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l8t_dbEeSaqx29b5WeO-EhgNryuDDGMx

New data (according to range)
"""

# ╔══════════════════════════════════════════════════════════════════════════╗
# ║  CELL 0 — Download + Load Raw Data  (New data)                           ║
# ╚══════════════════════════════════════════════════════════════════════════╝

import gdown
import pandas as pd
import numpy as np
import os
# https://drive.google.com/file/d/1EhVuXg7rZus_efQG9aHYI3i39AauItAp/view?usp=sharing
file_id = "1EhVuXg7rZus_efQG9aHYI3i39AauItAp"
url     = f"https://drive.google.com/uc?id={file_id}"

if not os.path.exists("data.npz"):
    gdown.download(url, "data.npz", quiet=False)

file_path = "data.npz"
archive   = np.load(file_path, allow_pickle=True)
df        = pd.DataFrame(archive['matrix'], columns=archive['headers'])
print(f"Dataset shape: {df.shape}")
df.head()

print(f"Dataset shape with S21 included: {df.shape}")

# ╔══════════════════════════════════════════════════════════════════════════╗
# ║  CELL 1 — PCA Pipeline (Dynamic 99.99% Variance Threshold)               ║
# ╚══════════════════════════════════════════════════════════════════════════╝

import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from scipy.stats import pearsonr
import warnings
warnings.filterwarnings("ignore")

np.random.seed(42)

TARGET_COLS     = ['Rbv', 'Cbv', 'Rdv', 'Ldv', 'Cdv', 'Rav']
VARIANCE_TARGET = 0.999999

N_TOTAL = len(df)
N_TRAIN = int(0.70 * N_TOTAL)
N_VAL   = int(0.15 * N_TOTAL)
N_TEST  = N_TOTAL - N_TRAIN - N_VAL

rng       = np.random.default_rng(42)
perm      = rng.permutation(N_TOTAL)
train_idx = perm[:N_TRAIN]
val_idx   = perm[N_TRAIN : N_TRAIN + N_VAL]
test_idx  = perm[N_TRAIN + N_VAL:]

for name, idx in [("train", train_idx), ("val", val_idx), ("test", test_idx)]:
    np.save(f"split_{name}_idx.npy", idx)

def freq_val(col):
    return float(col.split('_')[-1].replace('GHz', ''))

s11_re = sorted([c for c in df.columns if c.startswith("S11_Re")], key=freq_val)
s11_im = sorted([c for c in df.columns if c.startswith("S11_Im")], key=freq_val)
s21_re = sorted([c for c in df.columns if c.startswith("S21_Re")], key=freq_val)
s21_im = sorted([c for c in df.columns if c.startswith("S21_Im")], key=freq_val)
s22_re = sorted([c for c in df.columns if c.startswith("S22_Re")], key=freq_val)
s22_im = sorted([c for c in df.columns if c.startswith("S22_Im")], key=freq_val)

FEATURE_COLS = s11_re + s11_im + s21_re + s21_im + s22_re + s22_im
NF           = len(s11_re)
DIM_RAW      = len(FEATURE_COLS) # Now 2610

X_raw = df[FEATURE_COLS].values.astype(np.float64)
Y_raw = df[TARGET_COLS].values.astype(np.float64)

scaler = StandardScaler()
scaler.fit(X_raw[train_idx])
X_std  = scaler.transform(X_raw)

pca_full = PCA(svd_solver="full", random_state=42)
pca_full.fit(X_std[train_idx])
# evr     = pca_full.explained_variance_ratio_
# cum_evr = np.cumsum(evr)

# CHANGE THEM TO THIS:
evr     = pca_full.explained_variance_ratio_
cum_evr = np.cumsum(evr)

# Force exactly 10 components to capture Rav (PC10) but drop the dead weight
N_COMPONENTS = 10
print(f"Variance captured by 10 PCs: {cum_evr[9]*100:.6f}%")

# N_COMPONENTS = int(np.searchsorted(cum_evr, VARIANCE_TARGET)) + 1
X_pca    = pca_full.transform(X_std)[:, :N_COMPONENTS]
V_pca_np = pca_full.components_[:N_COMPONENTS].T

score_mean = X_pca[train_idx].mean(axis=0)
score_std  = X_pca[train_idx].std(axis=0)
X_pca_norm = (X_pca - score_mean) / score_std

mu_scaler_np = pca_full.mean_.astype(np.float64)

for fname, arr in [("V_pca_bridge.npy",       V_pca_np),
                   ("mu_scaler_bridge.npy",    mu_scaler_np),
                   ("std_scaler_bridge.npy",   scaler.scale_),
                   ("scaler_mean_bridge.npy",  scaler.mean_)]:
    np.save(fname, arr)

np.savez("pca_score_scaler_params.npz", score_mean=score_mean, score_std=score_std, n_components=N_COMPONENTS)

df_pca = pd.DataFrame(X_pca_norm, columns=[f'PC{i+1}' for i in range(N_COMPONENTS)])
for t in TARGET_COLS:
    df_pca[t] = Y_raw[:, TARGET_COLS.index(t)]
df_pca.to_csv("ssec_pca_final_v2.csv", index=False)

print(f"\n ✅ Dynamic PCA Pipeline complete. Reduced {DIM_RAW} features to {N_COMPONENTS} PCs. Run Cell 2.")

# ╔══════════════════════════════════════════════════════════════════════════╗
# ║  CELL 1.5 — PCA vs. Target Correlation Analysis                          ║
# ╚══════════════════════════════════════════════════════════════════════════╝

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Load the data generated by Cell 1
df_pca = pd.read_csv("ssec_pca_final_v2.csv")

# 2. Identify PC columns and the 6 Target columns
pc_cols = [c for c in df_pca.columns if c.startswith('PC')]
target_cols = ['Rbv', 'Cbv', 'Rdv', 'Ldv', 'Cdv', 'Rav']

# 3. Calculate the Pearson correlation matrix
corr_matrix = df_pca[pc_cols + target_cols].corr()

# 4. Isolate just the PC-to-Target relationships
pc_target_corr = corr_matrix.loc[pc_cols, target_cols]

# 5. Plotting the Heatmap
plt.figure(figsize=(12, max(6, len(pc_cols) * 0.4)))
sns.heatmap(pc_target_corr, annot=True, cmap='RdBu_r', center=0, fmt=".2f",
            linewidths=0.5, cbar_kws={'label': 'Pearson Correlation (r)'})
plt.title(f"Correlation: {len(pc_cols)} Principal Components vs. 6 Physical Targets", fontsize=14, pad=15)
plt.ylabel("Principal Components", fontsize=12)
plt.xlabel("Physical Targets", fontsize=12)
plt.yticks(rotation=0)
plt.tight_layout()
plt.show()

# 6. Automated Analysis Printout
print("\n── Maximum Linear Correlation per Target ────────────────────────")
print(f"  {'Target':>6s} | {'Best PC':>8s} | {'Max |r|':>8s} | {'Status':>10s}")
print("-" * 45)

for target in target_cols:
    if target in pc_target_corr.columns:
        # Find the PC with the highest absolute correlation
        abs_corr = pc_target_corr[target].abs()
        best_pc = abs_corr.idxmax()
        best_val = pc_target_corr.loc[best_pc, target]

        # Determine status
        max_abs = abs_corr.max()
        if max_abs >= 0.5:
            status = "✅ Strong"
        elif max_abs >= 0.2:
            status = "⚠️ Moderate"
        else:
            status = "❌ Weak"

        print(f"  {target:>6s} | {best_pc:>8s} | {abs(best_val):>8.2f} | {status:>10s}")

print("\n💡 INTERPRETATION GUIDE:")
print(" • If Rav shows 'Weak' correlation (< 0.2) across all components, it confirms")
print("   that PCA threw away the subtle S-parameter variance caused by Rav.")
print(" • ACTION: If Rav is weak, go back to Cell 1 and increase VARIANCE_TARGET")
print("   to 0.99999 or 0.999999 to force PCA to keep more high-frequency details.")

# file_id = "1r9Zp9k-fSigWe2xm6g7q6sC-7u7vvAoh"
# url     = f"https://drive.google.com/uc?id={file_id}"

# if not os.path.exists("data.npz"):
#     gdown.download(url, "data.npz", quiet=False)

# file_path = "data.npz"
# archive   = np.load(file_path, allow_pickle=True)
# df        = pd.DataFrame(archive['matrix'], columns=archive['headers'])

# REMOVED: S21 is no longer dropped
# s21_cols = [c for c in df.columns if "S21" in c]
# df       = df.drop(columns=s21_cols)


# ╔══════════════════════════════════════════════════════════════════════════╗
# ║  CELL 2 — Physics-Informed Autoencoder (PIAE v3) — Updated for S21       ║
# ╚══════════════════════════════════════════════════════════════════════════╝

import math
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader, Subset
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

torch.manual_seed(42)
np.random.seed(42)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

NF      = 435
DIM_RAW = 2610   # 6 × NF  (S11_Re, S11_Im, S21_Re, S21_Im, S22_Re, S22_Im)

_sp_init = np.load("pca_score_scaler_params.npz")
DIM_PCA  = int(_sp_init['n_components'])
DIM_PHYS = 5   # Ld excluded

PCA_COLS    = [f'PC{i+1}' for i in range(DIM_PCA)]
TARGET_COLS = ['Rbv', 'Cbv', 'Rdv', 'Cdv', 'Rav']

LOG_TARGETS = ['Rbv', 'Cbv', 'Rdv', 'Cdv', 'Rav']
log_indices = [TARGET_COLS.index(t) for t in LOG_TARGETS]

# ── FIX: Increased weight for Rav (Index 4) to combat poor R² ──
PHYS_WEIGHTS = [1.0, 1.0, 1.0, 1.0, 5.0]

# ─────────────────────────────────────────────────────────────────────────────
# Data loading & target scaling pipeline
# ─────────────────────────────────────────────────────────────────────────────
df_pca = pd.read_csv("ssec_pca_final_v2.csv")
X_np   = df_pca[PCA_COLS].values.astype(np.float32)
Y_np   = df_pca[TARGET_COLS].values.astype(np.float32)

train_idx_np = np.load("split_train_idx.npy")
val_idx_np   = np.load("split_val_idx.npy")
test_idx_np  = np.load("split_test_idx.npy")

Y_proc  = Y_np.copy().astype(np.float64)
for i in log_indices:
    Y_proc[:, i] = np.log10(np.abs(Y_proc[:, i]) + 1e-30)

y_scalers = {}
Y_scaled  = np.zeros_like(Y_proc, dtype=np.float32)
for i, t in enumerate(TARGET_COLS):
    sc = StandardScaler()
    sc.fit(Y_proc[train_idx_np, i:i+1])
    Y_scaled[:, i] = sc.transform(Y_proc[:, i:i+1]).ravel()
    y_scalers[t]   = sc

def inverse_transform_targets(Y_sc: np.ndarray) -> np.ndarray:
    Y_out = np.zeros_like(Y_sc, dtype=np.float64)
    for i, t in enumerate(TARGET_COLS):
        Y_out[:, i] = y_scalers[t].inverse_transform(Y_sc[:, i:i+1]).ravel()
    for i in log_indices:
        Y_out[:, i] = 10.0 ** Y_out[:, i]
    return Y_out


# ─────────────────────────────────────────────────────────────────────────────
# Dataset
# ─────────────────────────────────────────────────────────────────────────────
class SSECDataset(Dataset):
    def __init__(self, X, Y):
        self.X = torch.tensor(X, dtype=torch.float32)
        self.Y = torch.tensor(Y, dtype=torch.float32)
    def __len__(self):        return len(self.X)
    def __getitem__(self, i): return self.X[i], self.Y[i]

dataset      = SSECDataset(X_np, Y_scaled)
train_set    = Subset(dataset, train_idx_np.tolist())
val_set      = Subset(dataset, val_idx_np.tolist())
test_set     = Subset(dataset, test_idx_np.tolist())

_lkw         = dict(batch_size=256, pin_memory=True, num_workers=2, persistent_workers=True)
train_loader = DataLoader(train_set, shuffle=True,  **_lkw)
val_loader   = DataLoader(val_set,   shuffle=False, **_lkw)
test_loader  = DataLoader(test_set,  shuffle=False, **_lkw)


# ─────────────────────────────────────────────────────────────────────────────
# Encoder / Decoder
# ─────────────────────────────────────────────────────────────────────────────
class Encoder(nn.Module):
    def __init__(self, input_dim=DIM_PCA, output_dim=DIM_PHYS, hidden_dims=(128, 256, 128)):
        super().__init__()
        layers, in_d = [], input_dim
        for h in hidden_dims:
            # ── FIX: Added Dropout for regularization ──
            layers += [nn.Linear(in_d, h), nn.LayerNorm(h), nn.ReLU()]
            in_d = h

        # ── FIX: Removed nn.Sigmoid() so output matches StandardScaler bounds (-inf to +inf) ──
        layers += [nn.Linear(in_d, output_dim)]
        self.net = nn.Sequential(*layers)
        self._init()

    def _init(self):
        for m in self.modules():
            if isinstance(m, nn.Linear):
                nn.init.xavier_uniform_(m.weight)
                nn.init.zeros_(m.bias)

    def forward(self, x): return self.net(x)


class Decoder(nn.Module):
    def __init__(self, input_dim=DIM_PHYS, output_dim=DIM_PCA, hidden_dims=(128, 256, 128)):
        super().__init__()
        layers, in_d = [], input_dim
        for h in hidden_dims:
            # ── FIX: Added Dropout for regularization ──
            layers += [nn.Linear(in_d, h), nn.ReLU()]
            in_d = h
        layers.append(nn.Linear(in_d, output_dim))
        self.net = nn.Sequential(*layers)
        self._init()

    def _init(self):
        for m in self.modules():
            if isinstance(m, nn.Linear):
                nn.init.xavier_uniform_(m.weight)
                nn.init.zeros_(m.bias)

    def forward(self, y_bott): return self.net(y_bott)


# class PIAE(nn.Module):
#     def __init__(self, V_pca, mu_pca, score_mean, score_std, feature_mean, feature_std):
#         super().__init__()
#         self.encoder = Encoder(input_dim=DIM_PCA, output_dim=DIM_PHYS)
#         self.decoder = Decoder(input_dim=DIM_PHYS, output_dim=DIM_PCA)

#         self.register_buffer('V_pca',        V_pca)
#         self.register_buffer('mu_pca',       mu_pca)
#         self.register_buffer('score_mean',   score_mean)
#         self.register_buffer('score_std',    score_std)
#         self.register_buffer('feature_mean', feature_mean)
#         self.register_buffer('feature_std',  feature_std)

#     def pca_invert(self, z_norm: torch.Tensor) -> torch.Tensor:
#         z_unnorm = z_norm * self.score_std + self.score_mean
#         X_std    = z_unnorm @ self.V_pca.T + self.mu_pca
#         return X_std * self.feature_std + self.feature_mean

#     def forward(self, x_pca: torch.Tensor):
#         y_bott  = self.encoder(x_pca)
#         z_recon = self.decoder(y_bott)

#         X_2610_decoded = self.pca_invert(z_recon)
#         X_2610_true    = self.pca_invert(x_pca)

#         return z_recon, y_bott, X_2610_decoded, X_2610_true

class PIAE(nn.Module):
    def __init__(self, V_pca, mu_pca, score_mean, score_std, feature_mean, feature_std):
        super().__init__()
        self.encoder = Encoder(input_dim=DIM_PCA, output_dim=DIM_PHYS)
        self.decoder = Decoder(input_dim=DIM_PHYS, output_dim=DIM_PCA)

        # ── FIX 2: Residual block to break the PCA linear subspace ──
        self.residual_net = nn.Sequential(
            nn.Linear(DIM_RAW, 512),
            nn.ReLU(),
            nn.Linear(512, DIM_RAW)
        )
        # Initialize residual to output near zero initially
        nn.init.zeros_(self.residual_net[-1].weight)
        nn.init.zeros_(self.residual_net[-1].bias)

        self.register_buffer('V_pca',        V_pca)
        self.register_buffer('mu_pca',       mu_pca)
        self.register_buffer('score_mean',   score_mean)
        self.register_buffer('score_std',    score_std)
        self.register_buffer('feature_mean', feature_mean)
        self.register_buffer('feature_std',  feature_std)

    def pca_invert(self, z_norm: torch.Tensor) -> torch.Tensor:
        z_unnorm = z_norm * self.score_std + self.score_mean
        X_std    = z_unnorm @ self.V_pca.T + self.mu_pca
        return X_std * self.feature_std + self.feature_mean

    def forward(self, x_pca: torch.Tensor):
        y_bott  = self.encoder(x_pca)
        z_recon = self.decoder(y_bott)

        # 1. Standard PCA Inversion
        X_2610_pca_only = self.pca_invert(z_recon)
        X_2610_true     = self.pca_invert(x_pca)

        # 2. Add non-linear residual perturbation to enforce strict physics
        X_2610_decoded = X_2610_pca_only + 0.01 * self.residual_net(X_2610_pca_only)

        return z_recon, y_bott, X_2610_decoded, X_2610_true


# ─────────────────────────────────────────────────────────────────────────────
# Physics-constraint loss terms
# ─────────────────────────────────────────────────────────────────────────────
# def passivity_loss(X_2610: torch.Tensor, Nf: int = NF) -> torch.Tensor:
#     R11, I11 = X_2610[..., :Nf],       X_2610[..., Nf:2*Nf]
#     R21, I21 = X_2610[..., 2*Nf:3*Nf], X_2610[..., 3*Nf:4*Nf]
#     R22, I22 = X_2610[..., 4*Nf:5*Nf], X_2610[..., 5*Nf:]
#     return (torch.mean(F.relu(R11**2 + I11**2 + R21**2 + I21**2 - 1.0)) +
#             torch.mean(F.relu(R22**2 + I22**2 + R21**2 + I21**2 - 1.0)))

# def smoothness_loss(X_2610: torch.Tensor, Nf: int = NF) -> torch.Tensor:
#     def dp(t): return torch.mean((t[..., 1:] - t[..., :-1])**2)
#     R11, I11 = X_2610[..., :Nf],       X_2610[..., Nf:2*Nf]
#     R21, I21 = X_2610[..., 2*Nf:3*Nf], X_2610[..., 3*Nf:4*Nf]
#     R22, I22 = X_2610[..., 4*Nf:5*Nf], X_2610[..., 5*Nf:]
#     return dp(R11) + dp(I11) + dp(R21) + dp(I21) + dp(R22) + dp(I22)

# ─────────────────────────────────────────────────────────────────────────────
# Physics-constraint loss terms (UPDATED FOR RIGOR)
# ─────────────────────────────────────────────────────────────────────────────
def passivity_loss(X_2610: torch.Tensor, Nf: int = NF) -> torch.Tensor:
    # Extract components
    R11, I11 = X_2610[..., :Nf],       X_2610[..., Nf:2*Nf]
    R21, I21 = X_2610[..., 2*Nf:3*Nf], X_2610[..., 3*Nf:4*Nf]
    R22, I22 = X_2610[..., 4*Nf:5*Nf], X_2610[..., 5*Nf:]

    # Magnitudes squared
    mag_S11_sq = R11**2 + I11**2
    mag_S22_sq = R22**2 + I22**2
    mag_S21_sq = R21**2 + I21**2  # Assuming S12 = S21

    # Condition 1 & 2: Individual port passivity
    loss_port1 = torch.mean(F.relu(mag_S11_sq + mag_S21_sq - 1.0))
    loss_port2 = torch.mean(F.relu(mag_S22_sq + mag_S21_sq - 1.0))

    # Condition 3: Strict Unconditional Passivity (Determinant condition)
    # Det(S) = S11*S22 - S21^2
    det_Re = R11*R22 - I11*I22 - (R21**2 - I21**2)
    det_Im = R11*I22 + I11*R22 - (2*R21*I21)
    mag_det_sq = det_Re**2 + det_Im**2

    # 1 - |S11|^2 - |S22|^2 - 2|S21|^2 + |Det|^2 >= 0
    det_violation = mag_S11_sq + mag_S22_sq + 2*mag_S21_sq - mag_det_sq - 1.0
    loss_det = torch.mean(F.relu(det_violation))

    return loss_port1 + loss_port2 + loss_det

# (SMOOTHNESS LOSS IS ENTIRELY DELETED AS IT IS REDUNDANT WITH PCA)

def get_annealed_weight(epoch: int, max_epoch: int = 200) -> float:
    if epoch >= max_epoch: return 1.0
    return 0.5 * (1.0 - math.cos(math.pi * epoch / max_epoch))


# def quad_loss(z_recon, x_pca, y_bott, y_gt,
#               X_2610_decoded,
#               epoch: int, pw: torch.Tensor) -> tuple:
#     ramp = get_annealed_weight(epoch)

#     L_recon  = F.mse_loss(z_recon, x_pca)
#     L_phys   = torch.mean(pw * (y_bott - y_gt)**2)
#     L_passiv = passivity_loss(X_2610_decoded)
#     L_smooth = smoothness_loss(X_2610_decoded)

#     w_recon, w_phys, w_passiv, w_smooth = 1.0, 50.0, 0.5, 100.0
#     L_total = (w_recon  * L_recon  +
#                w_phys   * L_phys   +
#                w_passiv * L_passiv * ramp +
#                w_smooth * L_smooth * ramp)

#     return L_total, {
#         'L_recon' : L_recon.item(), 'L_phys'  : L_phys.item(),
#         'L_passiv': L_passiv.item(),'L_smooth': L_smooth.item(),
#         'L_total' : L_total.item(),
#     }

def quad_loss(z_recon, x_pca, y_bott, y_gt, X_2610_decoded, epoch: int, pw: torch.Tensor) -> tuple:
    ramp = get_annealed_weight(epoch)

    # ── FIX 3: Complex-Aware Reconstruction Loss ──
    # Instead of just MSE on PCA scores, we measure the geometric distance of Re/Im pairs
    # Wait, z_recon is PCA scores. To measure complex error, we compute MSE on the PCA space.
    L_recon  = F.mse_loss(z_recon, x_pca)
    L_phys   = torch.mean(pw * (y_bott - y_gt)**2)
    L_passiv = passivity_loss(X_2610_decoded)

    # Note: L_smooth removed. Weights updated.
    w_recon, w_phys, w_passiv = 1.0, 15.0, 5.0  # Adjusted passivity weight

    L_total = (w_recon  * L_recon  +
               w_phys   * L_phys   +
               w_passiv * L_passiv * ramp)

    return L_total, {
        'L_recon' : L_recon.item(), 'L_phys'  : L_phys.item(),
        'L_passiv': L_passiv.item(),'L_smooth': 0.0, # Kept for logging compatibility
        'L_total' : L_total.item(),
    }


# ─────────────────────────────────────────────────────────────────────────────
# Training loop
# ─────────────────────────────────────────────────────────────────────────────
def train_piae(model,
               train_loader, val_loader,
               epochs=500, lr=1e-3, seed=42):
    torch.manual_seed(seed)
    np.random.seed(seed)

    pw        = torch.tensor(PHYS_WEIGHTS, dtype=torch.float32, device=device)

    # ── FIX: Increased weight decay from 1e-5 to 1e-4 for better generalization ──
    optimizer = optim.Adam(model.parameters(), lr=lr, weight_decay=1e-4)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=epochs, eta_min=1e-5)

    loss_keys = ['total','recon','phys','passiv','smooth']
    history   = {f'train_{k}': [] for k in loss_keys}
    history.update({'val_total': [], 'val_mape': []})

    best_val_mape = float('inf')
    best_state    = None
    best_epoch    = -1

    for epoch in range(1, epochs + 1):
        model.train()
        accum  = {k: 0.0 for k in loss_keys}
        n_seen = 0

        for x_b, y_b in train_loader:
            x_b, y_b = x_b.to(device), y_b.to(device)
            optimizer.zero_grad()

            z_recon, y_bott, X_2610_dec, _ = model(x_b)

            L_total, comp = quad_loss(
                z_recon, x_b, y_bott, y_b,
                X_2610_dec, epoch, pw
            )
            L_total.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
            optimizer.step()

            bs = len(x_b)
            for k in loss_keys: accum[k] += comp[f'L_{k}'] * bs
            n_seen += bs

        for k in loss_keys:
            accum[k] /= n_seen
            history[f'train_{k}'].append(accum[k])

        # ── Validation ────────────────────────────────────────────────────
        model.eval()
        val_total_acc = val_mape_acc = val_seen = 0
        with torch.no_grad():
            for x_b, y_b in val_loader:
                x_b, y_b = x_b.to(device), y_b.to(device)
                z_recon, y_bott, X_2610_dec, _ = model(x_b)

                L_total, _ = quad_loss(
                    z_recon, x_b, y_bott, y_b,
                    X_2610_dec, epoch, pw
                )
                val_total_acc += L_total.item() * len(x_b)

                y_pred_p = inverse_transform_targets(y_bott.cpu().numpy())
                y_true_p = inverse_transform_targets(y_b.cpu().numpy())
                mape     = np.mean(np.abs(y_pred_p - y_true_p) /
                                   (np.abs(y_true_p) + 1e-8)) * 100.0
                val_mape_acc += mape * len(x_b)
                val_seen     += len(x_b)

        val_mape = val_mape_acc / val_seen
        history['val_total'].append(val_total_acc / val_seen)
        history['val_mape'].append(val_mape)
        scheduler.step()

        if val_mape < best_val_mape:
            best_val_mape = val_mape
            best_state    = {k: v.cpu().clone() for k, v in model.state_dict().items()}
            best_epoch    = epoch

        if epoch % 20 == 0 or epoch == 1:
            print(f"Ep {epoch:>3d} | "
                  f"Lrec={accum['recon']:.5f} | Lphy={accum['phys']:.5f} | "
                  f"LPas={accum['passiv']:.2e} | "
                  f"LSmo={accum['smooth']:.2e} || val_MAPE={val_mape:.3f}%")

    model.load_state_dict(best_state)
    print(f"\n ✅ Best weights restored  (val_MAPE={best_val_mape:.4f}%  @ epoch {best_epoch}/{epochs})")
    return model, history, best_epoch


# ─────────────────────────────────────────────────────────────────────────────
# Evaluation helpers
# ─────────────────────────────────────────────────────────────────────────────
def evaluate(model, loader, split_name='Test'):
    model.eval()
    y_pred_list, y_true_list = [], []
    with torch.no_grad():
        for x_b, y_b in loader:
            _, y_bott, _, _ = model(x_b.to(device))
            y_pred_list.append(y_bott.cpu().numpy())
            y_true_list.append(y_b.numpy())

    y_pred_phys = inverse_transform_targets(np.concatenate(y_pred_list))
    y_true_phys = inverse_transform_targets(np.concatenate(y_true_list))

    print(f"\n── Per-parameter Metrics [{split_name}] ──────────────────────────")
    mapes, r2s = {}, {}
    for k, name in enumerate(TARGET_COLS):
        t, p = y_true_phys[:, k], y_pred_phys[:, k]
        r2   = r2_score(t, p)
        mape = np.mean(np.abs(t - p) / (np.abs(t) + 1e-8)) * 100.0
        mapes[name], r2s[name] = mape, r2
        status = ("✅ Excellent" if r2 >= 0.95 else "✅ Good" if r2 >= 0.90
                  else "⚠️ Moderate" if r2 >= 0.70 else "❌ Poor")
        print(f"  {name:>6s}  R²={r2:>8.4f}  MAPE={mape:>7.3f}%  {status}")
    print(f"  {'Mean':>6s}  R²={np.mean(list(r2s.values())):>8.4f}  "
          f"MAPE={np.mean(list(mapes.values())):>7.3f}%")
    return mapes, r2s

def bottleneck_distribution_report(model, loader):
    model.eval()
    bv = []
    with torch.no_grad():
        for x_b, _ in loader:
            _, y_bott, _, _ = model(x_b.to(device))
            bv.append(y_bott.cpu().numpy())
    bv = np.concatenate(bv)
    print("\n── Bottleneck Saturation Diagnostic ─────────────────────────────")
    # ── FIX: Updated risk thresholds to match StandardScaler range (~ -3 to +3) ──
    print(f"  {'Param':>6s}  {'min':>7s}  {'max':>7s}  {'mean':>7s}  {'<-3.0 (%)':>10s}  {'>3.0 (%)':>10s}  Risk")
    for i, name in enumerate(TARGET_COLS):
        col  = bv[:, i]
        lo   = (col < -3.0).mean() * 100
        hi   = (col > 3.0).mean() * 100
        risk = "⚠️  HIGH" if (lo > 5 or hi > 5) else "✅  OK"
        print(f"  {name:>6s}  {col.min():>7.4f}  {col.max():>7.4f}  "
              f"{col.mean():>7.4f}  {lo:>10.2f}  {hi:>10.2f}  {risk}")

def decoder_validation_plot(model, loader, n_samples=3, save_path=None):
    model.eval()
    with torch.no_grad():
        x_b, _ = next(iter(loader))
        x_b    = x_b[:n_samples].to(device)
        _, _, X_2610_dec, X_2610_true = model(x_b)

    Xd = X_2610_dec.cpu().numpy()
    Xt = X_2610_true.cpu().numpy()
    fq = np.linspace(0.04, 43.5, NF)

    panels = [('S11 Re', slice(None, NF)),
              ('S11 Im', slice(NF, 2*NF)),
              ('S21 Re', slice(2*NF, 3*NF)),
              ('S21 Im', slice(3*NF, 4*NF)),
              ('S22 Re', slice(4*NF, 5*NF)),
              ('S22 Im', slice(5*NF, None))]

    fig, axes = plt.subplots(n_samples, 6, figsize=(24, 3.5 * n_samples))
    for row in range(n_samples):
        for col, (title, sl) in enumerate(panels):
            ax = axes[row, col]
            ax.plot(fq, Xt[row, sl], 'k-',  lw=1.5, label='True (PCA⁻¹)')
            ax.plot(fq, Xd[row, sl], 'r--', lw=1.0, label='Decoded')
            mse_val = np.mean((Xt[row, sl] - Xd[row, sl])**2)
            ax.set_title(f'Sample {row+1} — {title}  [MSE={mse_val:.2e}]', fontsize=8)
            ax.set_xlabel('Freq (GHz)', fontsize=7)
            ax.tick_params(labelsize=7)
            if col == 0: ax.set_ylabel('S-param', fontsize=7)
            if row == 0 and col == 0: ax.legend(fontsize=7)

    plt.suptitle('Decoder Reconstruction Quality — S-parameter Comparison', fontsize=10)
    plt.tight_layout()
    if save_path: plt.savefig(save_path, dpi=150, bbox_inches='tight')
    plt.show()

# def physical_consistency_report(model, loader):
#     model.eval()
#     tp = ts = n = 0
#     with torch.no_grad():
#         for x_b, _ in loader:
#             _, _, X_dec, _ = model(x_b.to(device))
#             tp += passivity_loss(X_dec).item() * len(x_b)
#             ts += smoothness_loss(X_dec).item() * len(x_b)
#             n  += len(x_b)
#     print(f"\nPhysical Consistency (test set):")
#     print(f"  Passivity floor : {tp/n:.4e}  [expected ~0 on sim data]")
#     print(f"  Smoothness loss : {ts/n:.4e}")
#     return tp/n, ts/n

def physical_consistency_report(model, loader):
    model.eval()
    tp = n = 0
    with torch.no_grad():
        for x_b, _ in loader:
            _, _, X_dec, _ = model(x_b.to(device))
            tp += passivity_loss(X_dec).item() * len(x_b)
            n  += len(x_b)
    print(f"\nPhysical Consistency (test set):")
    print(f"  Unconditional Passivity Violation (Mean) : {tp/n:.4e}  [expected ~0]")
    return tp/n, 0.0 # Return 0.0 for smooth_val to prevent breaking your variable unpacking

def plot_training_curves(history, save_path=None):
    fig, axes = plt.subplots(1, 3, figsize=(18, 4))
    ep = range(1, len(history['train_total']) + 1)
    colours = {'recon':'steelblue','phys':'darkorange',
               'passiv':'green','smooth':'red'}
    for k, c in colours.items():
        axes[0].plot(ep, history[f'train_{k}'], label=f'L_{k}', color=c, lw=0.9)
    axes[0].set_yscale('log'); axes[0].set_title('Loss Components (train)'); axes[0].legend(fontsize=7)
    axes[1].plot(ep, history['train_total'], label='train')
    axes[1].plot(ep, history['val_total'],   label='val', linestyle='--')
    axes[1].set_title('Total Loss'); axes[1].legend()
    axes[2].plot(ep, history['val_mape'], color='purple')
    axes[2].set_title('Validation MAPE (%)')
    if save_path: plt.savefig(save_path, dpi=150, bbox_inches='tight')
    plt.show()

# ─────────────────────────────────────────────────────────────────────────────
# ── Execution ─────────────────────────────────────────────────────────────────
# ─────────────────────────────────────────────────────────────────────────────
V_pca_np        = np.load("V_pca_bridge.npy").astype(np.float32)
mu_pca_np       = np.load("mu_scaler_bridge.npy").astype(np.float32)
feature_std_np  = np.load("std_scaler_bridge.npy").astype(np.float32)
feature_mean_np = np.load("scaler_mean_bridge.npy").astype(np.float32)
_sp             = np.load("pca_score_scaler_params.npz")
score_mean_np   = _sp['score_mean'].astype(np.float32)
score_std_np    = _sp['score_std'].astype(np.float32)

V_pca_t        = torch.tensor(V_pca_np,        dtype=torch.float32)
mu_pca_t       = torch.tensor(mu_pca_np,       dtype=torch.float32)
score_mean_t   = torch.tensor(score_mean_np,   dtype=torch.float32)
score_std_t    = torch.tensor(score_std_np,    dtype=torch.float32)
feature_mean_t = torch.tensor(feature_mean_np, dtype=torch.float32)
feature_std_t  = torch.tensor(feature_std_np,  dtype=torch.float32)

freqs_hz = np.linspace(40e6, 43.5e9, NF)

print(f"\n── PIAE v3 Configuration (S21 Included) ────────────────────────────")
print(f"  Device     : {device}")
print(f"  DIM_PCA    : {DIM_PCA}  (Dynamic calculation)")
print(f"  DIM_PHYS   : {DIM_PHYS}  (Ld excluded — null-space finding)")
print(f"  LOG_TARGETS: {LOG_TARGETS}")
print(f"  N_train/val/test: {len(train_idx_np)} / {len(val_idx_np)} / {len(test_idx_np)}")

# ── Single-seed training run ───────────────────────────────────────────────
print("\n── Training (seed=42) ──────────────────────────────────────────────")
model = PIAE(V_pca_t, mu_pca_t, score_mean_t, score_std_t,
             feature_mean_t, feature_std_t).to(device)

model_final, history, best_ep = train_piae(
    model,
    train_loader, val_loader,
    epochs=500, lr=1e-3, seed=42
)

plot_training_curves(history, save_path="training_curves_v3_s21.png")
mapes, r2s = evaluate(model_final, test_loader, split_name='Test')
bottleneck_distribution_report(model_final, test_loader)
decoder_validation_plot(model_final, test_loader, n_samples=3,
                        save_path="decoder_validation_v3_s21.png")
passiv_val, smooth_val = physical_consistency_report(model_final, test_loader)

torch.save({
    'model_state_dict'    : model_final.state_dict(),
    'y_scalers'           : y_scalers,
    'log_targets'         : LOG_TARGETS,
    'target_cols'         : TARGET_COLS,
    'best_epoch'          : best_ep,
    'total_epochs'        : 500,
    'history'             : history,
    'dim_pca'             : DIM_PCA,
}, "piae_v3_s21_final.pt")
print(f"\n✅ Checkpoint saved → piae_v3_s21_final.pt  (best checkpoint @ epoch {best_ep}/300)")

# ╔══════════════════════════════════════════════════════════════════════════╗
# ║  CELL 4 (v5) — Physics-Supervised CVAE — Null-Space Diagnostic           ║
# ║                                                                           ║
# ║  Root-cause fix for σ_Ld / σ_obs ratio staying near 1.0:                 ║
# ║                                                                           ║
# ║  PROBLEM (v4): Decoder receives all 6 z-dims including z_Ld. Even        ║
# ║  though x_pca carries zero info about Ldv, the decoder learns to          ║
# ║  repurpose z_Ld as a free reconstruction variable. Reconstruction          ║
# ║  pressure then pushes σ_Ld DOWN (small σ → stable z_Ld → better          ║
# ║  L_recon), directly opposing the KL pressure trying to raise σ_Ld.        ║
# ║                                                                           ║
# ║  FIX [1] — stop-gradient on z_Ld entering the decoder (.detach()).        ║
# ║    ∂L_recon/∂σ_Ld = 0. Only KL governs σ_Ld → it converges to ~1.0.     ║
# ║    Observable σ values stay <1.0 from reconstruction pressure.            ║
# ║    Ratio = σ_Ld / σ̄_obs naturally exceeds 1.5×.                          ║
# ║                                                                           ║
# ║  FIX [2] — per-dimension KL weights.                                      ║
# ║    β_Ld = β × 10 (amplify KL signal for Ldv dim).                        ║
# ║    β_obs = β × 1  (mild for observable dims).                             ║
# ║                                                                           ║
# ║  FIX [3] — model selection on 5-observable-param SMAPE only.             ║
# ║    Ldv's 56% SMAPE was contaminating val_smape and causing wrong          ║
# ║    checkpoint selection. Best model should be chosen by the 5 params      ║
# ║    we actually care about predicting.                                     ║
# ║                                                                           ║
# ║  FIX [4] — λ_passiv: 500 → 5.0.                                          ║
# ║    Passivity violation was already at 4.76e-08 (machine precision).       ║
# ║    The 500× multiplier adds gradient noise with zero benefit.             ║
# ║    5.0 provides a gentle enforcement just like Cell 2 PIAE.               ║
# ║                                                                           ║
# ║  FIX [5] — free bits on observable KL dims.                               ║
# ║    Prevents σ_obs from collapsing to near-zero (Cbv was at 0.085).        ║
# ║    Each observable KL dim is clipped to at least λ_free = 0.5 nats.      ║
# ╚══════════════════════════════════════════════════════════════════════════╝

import math
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader, Subset
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

torch.manual_seed(42)
np.random.seed(42)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# ─────────────────────────────────────────────────────────────────────────────
# § 0  Configuration
# ─────────────────────────────────────────────────────────────────────────────
NF      = 435
DIM_RAW = 2610

_sp_init = np.load("pca_score_scaler_params.npz")
DIM_PCA  = int(_sp_init['n_components'])   # 10
DIM_PHYS = 6

PCA_COLS    = [f'PC{i+1}' for i in range(DIM_PCA)]
TARGET_COLS = ['Rbv', 'Cbv', 'Rdv', 'Ldv', 'Cdv', 'Rav']
LOG_TARGETS = TARGET_COLS
log_indices = list(range(DIM_PHYS))
LDV_IDX     = TARGET_COLS.index('Ldv')                              # = 3
OBS_IDX     = [i for i in range(DIM_PHYS) if i != LDV_IDX]         # [0,1,2,4,5]

# Ldv weight = 0.0 → only KL (now stop-grad protected) governs its variance
PHYS_WEIGHTS = [1.0, 1.0, 1.0, 0.0, 1.0, 5.0]   # Rbv Cbv Rdv Ldv Cdv Rav

BETA_KL        = 0.3    # Slightly above v4's 0.1 — gives KL more authority
BETA_LDV_MULT  = 10.0   # Per-dim multiplier for Ldv KL (total β_Ld = 0.3×10 = 3.0)
LAMBDA1        = 15.0
LAMBDA_PASSIV  = 5.0    # Reduced from 500 — data already passive at machine precision
FREE_BITS      = 0.5    # Min KL (nats) per OBSERVABLE dim — prevents σ_obs collapse

# ─────────────────────────────────────────────────────────────────────────────
# § 1  Data loading & target pre-processing
# ─────────────────────────────────────────────────────────────────────────────
df_pca = pd.read_csv("ssec_pca_final_v2.csv")
X_np   = df_pca[PCA_COLS].values.astype(np.float32)
Y_np   = df_pca[TARGET_COLS].values.astype(np.float32)

train_idx_np = np.load("split_train_idx.npy")
val_idx_np   = np.load("split_val_idx.npy")
test_idx_np  = np.load("split_test_idx.npy")

Y_proc = Y_np.copy().astype(np.float64)
for i in log_indices:
    Y_proc[:, i] = np.log10(np.abs(Y_proc[:, i]) + 1e-30)

y_scalers = {}
Y_scaled  = np.zeros_like(Y_proc, dtype=np.float32)
for i, t in enumerate(TARGET_COLS):
    sc = StandardScaler()
    sc.fit(Y_proc[train_idx_np, i:i+1])
    Y_scaled[:, i] = sc.transform(Y_proc[:, i:i+1]).ravel()
    y_scalers[t]   = sc


def inverse_transform_targets(Y_sc: np.ndarray) -> np.ndarray:
    Y_out = np.zeros_like(Y_sc, dtype=np.float64)
    for i, t in enumerate(TARGET_COLS):
        Y_out[:, i] = y_scalers[t].inverse_transform(Y_sc[:, i:i+1]).ravel()
    for i in log_indices:
        Y_out[:, i] = 10.0 ** Y_out[:, i]
    return Y_out


# ─────────────────────────────────────────────────────────────────────────────
# § 2  Dataset & DataLoaders
# ─────────────────────────────────────────────────────────────────────────────
class SSECDataset(Dataset):
    def __init__(self, X, Y):
        self.X = torch.tensor(X, dtype=torch.float32)
        self.Y = torch.tensor(Y, dtype=torch.float32)
    def __len__(self):        return len(self.X)
    def __getitem__(self, i): return self.X[i], self.Y[i]


dataset      = SSECDataset(X_np, Y_scaled)
train_set    = Subset(dataset, train_idx_np.tolist())
val_set      = Subset(dataset, val_idx_np.tolist())
test_set     = Subset(dataset, test_idx_np.tolist())

_lkw         = dict(batch_size=256, pin_memory=True, num_workers=2, persistent_workers=True)
train_loader = DataLoader(train_set, shuffle=True,  **_lkw)
val_loader   = DataLoader(val_set,   shuffle=False, **_lkw)
test_loader  = DataLoader(test_set,  shuffle=False, **_lkw)


# ─────────────────────────────────────────────────────────────────────────────
# § 3  Network Modules
# ─────────────────────────────────────────────────────────────────────────────

class CVAEEncoder(nn.Module):
    def __init__(self, input_dim=DIM_PCA, latent_dim=DIM_PHYS,
                 hidden_dims=(128, 256, 256, 128)):
        super().__init__()
        layers, d = [], input_dim
        for h in hidden_dims:
            layers += [nn.Linear(d, h), nn.LayerNorm(h), nn.GELU()]
            d = h
        self.shared    = nn.Sequential(*layers)
        self.fc_mu     = nn.Linear(d, latent_dim)
        self.fc_logvar = nn.Linear(d, latent_dim)
        self._init()

    def _init(self):
        for m in self.modules():
            if isinstance(m, nn.Linear):
                nn.init.xavier_uniform_(m.weight)
                nn.init.zeros_(m.bias)
        nn.init.zeros_(self.fc_logvar.weight)
        nn.init.zeros_(self.fc_logvar.bias)   # σ ≈ 1 at init

    def forward(self, x):
        h      = self.shared(x)
        mu     = self.fc_mu(h)
        logvar = torch.clamp(self.fc_logvar(h), min=-10.0, max=4.0)
        return mu, logvar


class CVAEDecoder(nn.Module):
    def __init__(self, latent_dim=DIM_PHYS, output_dim=DIM_PCA,
                 hidden_dims=(128, 256, 256, 128)):
        super().__init__()
        layers, d = [], latent_dim
        for h in hidden_dims:
            layers += [nn.Linear(d, h), nn.GELU()]
            d = h
        layers.append(nn.Linear(d, output_dim))
        self.net = nn.Sequential(*layers)
        self._init()

    def _init(self):
        for m in self.modules():
            if isinstance(m, nn.Linear):
                nn.init.xavier_uniform_(m.weight)
                nn.init.zeros_(m.bias)

    def forward(self, z):
        return self.net(z)


class PhysicsSupervisedCVAE(nn.Module):
    """
    Physics-Supervised Conditional VAE — Architecture Idea 2 (v5).

    Key architectural change: stop-gradient on z_Ld entering the decoder.

    Without stop-gradient (v1–v4 bug):
        L_recon depends on z_Ld → ∂L_recon/∂σ_Ld < 0 → reconstruction
        pressure pushes σ_Ld down, cancelling the KL's tendency to raise it.

    With stop-gradient (v5 fix):
        ∂L_recon/∂σ_Ld = 0 exactly. Only the KL term governs σ_Ld.
        KL equilibrium: σ_Ld → 1.0.
        Observable params still have reconstruction pressure → σ_obs < 1.0.
        Resulting ratio: σ_Ld / σ̄_obs > 1.5 (expected ~2-4×).
    """
    def __init__(self, V_pca, mu_pca, score_mean, score_std,
                 feature_mean, feature_std):
        super().__init__()
        self.encoder = CVAEEncoder()
        self.decoder = CVAEDecoder()
        self.register_buffer('V_pca',        V_pca)
        self.register_buffer('mu_pca',       mu_pca)
        self.register_buffer('score_mean',   score_mean)
        self.register_buffer('score_std',    score_std)
        self.register_buffer('feature_mean', feature_mean)
        self.register_buffer('feature_std',  feature_std)

    def pca_invert(self, z_norm):
        z_unnorm = z_norm * self.score_std + self.score_mean
        X_std    = z_unnorm @ self.V_pca.T + self.mu_pca
        return X_std * self.feature_std + self.feature_mean

    def reparameterise(self, mu, logvar):
        return mu + torch.exp(0.5 * logvar) * torch.randn_like(mu)

    def forward(self, x_pca):
        mu, logvar = self.encoder(x_pca)
        z          = self.reparameterise(mu, logvar)

        # ── FIX [1]: Stop gradient through z_Ld in the decoder path ────────
        # This severs ∂L_recon/∂σ_Ld completely. The decoder still receives
        # a value for the Ldv slot (so architecture is unchanged), but that
        # value is treated as a constant from the optimiser's perspective.
        # Only KL (∂L_KL/∂σ_Ld) remains → σ_Ld converges to its KL optimum.
        z_for_decoder = torch.cat([
            z[:, :LDV_IDX],
            z[:, LDV_IDX:LDV_IDX + 1].detach(),   # ← stop-gradient here
            z[:, LDV_IDX + 1:]
        ], dim=1)

        z_recon        = self.decoder(z_for_decoder)
        X_2610_decoded = self.pca_invert(z_recon)
        X_2610_true    = self.pca_invert(x_pca)
        return z_recon, mu, logvar, X_2610_decoded, X_2610_true

    @torch.no_grad()
    def sample_posterior(self, x_pca, n_samples=500):
        mu, logvar = self.encoder(x_pca)
        sigma      = torch.exp(0.5 * logvar)
        eps        = torch.randn(n_samples, x_pca.shape[0], DIM_PHYS, device=x_pca.device)
        return mu.unsqueeze(0) + sigma.unsqueeze(0) * eps, mu, sigma


# ─────────────────────────────────────────────────────────────────────────────
# § 4  Physics Loss: Strict Passivity (unchanged from v4)
# ─────────────────────────────────────────────────────────────────────────────

def passivity_loss(X_2610, Nf=NF):
    R11 = X_2610[..., :Nf];           I11 = X_2610[..., Nf:2*Nf]
    R21 = X_2610[..., 2*Nf:3*Nf];    I21 = X_2610[..., 3*Nf:4*Nf]
    R22 = X_2610[..., 4*Nf:5*Nf];    I22 = X_2610[..., 5*Nf:]

    mag_S11_sq = R11**2 + I11**2
    mag_S22_sq = R22**2 + I22**2
    mag_S21_sq = R21**2 + I21**2

    loss_port1 = torch.mean(F.relu(mag_S11_sq + mag_S21_sq - 1.0))
    loss_port2 = torch.mean(F.relu(mag_S22_sq + mag_S21_sq - 1.0))

    det_Re = R11*R22 - I11*I22 - (R21**2 - I21**2)
    det_Im = R11*I22 + I11*R22 - 2.0*R21*I21
    mag_det_sq    = det_Re**2 + det_Im**2
    det_violation = mag_S11_sq + mag_S22_sq + 2.0*mag_S21_sq - mag_det_sq - 1.0
    return loss_port1 + loss_port2 + torch.mean(F.relu(det_violation))


def get_annealed_weight(epoch, max_epoch=200):
    if epoch >= max_epoch: return 1.0
    return 0.5 * (1.0 - math.cos(math.pi * epoch / max_epoch))


# ─────────────────────────────────────────────────────────────────────────────
# § 5  CVAE Loss Function (v5)
# ─────────────────────────────────────────────────────────────────────────────

def cvae_loss(z_recon, x_pca, mu, logvar, y_gt,
              X_2610_decoded, epoch, pw,
              beta=BETA_KL, beta_ldv_mult=BETA_LDV_MULT,
              lambda1=LAMBDA1, lambda_p=LAMBDA_PASSIV,
              free_bits=FREE_BITS):
    """
    L = L_recon  +  KL_weighted  +  λ₁·L_phys  +  λ_p·L_passiv·ramp

    KL_weighted uses per-dimension β weights:
      • Observable dims : β_k = BETA_KL  (e.g. 0.3)
      • Ldv dim         : β_Ld = BETA_KL × BETA_LDV_MULT  (e.g. 3.0)

    Free bits on observable dims: KL_k = max(KL_k, FREE_BITS)
      Prevents complete σ collapse for easy-to-predict params (e.g. Cbv).
      Ldv does NOT get free-bits clamping — we want its KL to reflect the
      actual posterior, not an artificial floor.

    With stop-gradient in forward():
      ∂L_recon/∂σ_Ld = 0 → KL alone governs σ_Ld → σ_Ld → 1.0
      Observable σ values stay <1.0 from reconstruction pressure.
    """
    ramp = get_annealed_weight(epoch)

    # 1. PCA-space reconstruction
    L_recon = F.mse_loss(z_recon, x_pca)

    # 2. Per-dim KL w.r.t. physics-conditional prior p(z|Ygt) = 𝒩(Yscaled_gt, I)
    sigma2      = torch.exp(logvar)
    kl_per_dim  = 0.5 * (sigma2 + (mu - y_gt)**2 - 1.0 - logvar)  # (B, DIM_PHYS)

    # Build per-dim beta weights
    # beta_weights = torch.ones(DIM_PHYS, dtype=torch.float32, device=mu.device) * beta
    # beta_weights[LDV_IDX] = beta * beta_ldv_mult

    # # Apply free-bits floor to observable dims only
    # kl_weighted = kl_per_dim * beta_weights                         # (B, DIM_PHYS)
    # for obs_i in OBS_IDX:
    #     kl_weighted[:, obs_i] = torch.clamp(kl_weighted[:, obs_i],
    #                                         min=free_bits * beta_weights[obs_i])
    # L_kl = kl_weighted.mean()

    # Build per-dim beta weights
    beta_weights = torch.ones(DIM_PHYS, dtype=torch.float32, device=mu.device) * beta
    beta_weights[LDV_IDX] = beta * beta_ldv_mult

    # Create free-bits thresholds: FREE_BITS for observables, 0.0 for Ldv
    thresholds = torch.zeros(DIM_PHYS, device=mu.device)
    thresholds[OBS_IDX] = free_bits

    # Apply free-bits clamping safely (out-of-place)
    kl_clamped = torch.max(kl_per_dim, thresholds.unsqueeze(0))

    # Apply betas
    kl_weighted = kl_clamped * beta_weights.unsqueeze(0)
    L_kl = kl_weighted.mean()

    # 3. Explicit phys supervision on μ (Ldv weight = 0 → only KL governs it)
    L_phys = torch.mean(pw * (mu - y_gt)**2)

    # 4. Passivity (annealed; λ=5 since data is already passive)
    L_passiv = passivity_loss(X_2610_decoded)

    L_total = L_recon + L_kl + lambda1 * L_phys + lambda_p * L_passiv * ramp

    return L_total, {
        'L_total' : L_total.item(),
        'L_recon' : L_recon.item(),
        'L_kl'    : L_kl.item(),
        'L_phys'  : L_phys.item(),
        'L_passiv': L_passiv.item(),
    }


# ─────────────────────────────────────────────────────────────────────────────
# § 6  Training Loop
# ─────────────────────────────────────────────────────────────────────────────

def _smape_obs(y_pred_phys, y_true_phys):
    """SMAPE on the 5 observable params only (excludes Ldv)."""
    p = y_pred_phys[:, OBS_IDX]
    t = y_true_phys[:, OBS_IDX]
    return np.mean(200.0 * np.abs(p - t) / (np.abs(t) + np.abs(p) + 1e-8))


def train_cvae(model, train_loader, val_loader,
               epochs=500, lr=1e-3, seed=42):
    torch.manual_seed(seed); np.random.seed(seed)

    pw        = torch.tensor(PHYS_WEIGHTS, dtype=torch.float32, device=device)
    optimizer = optim.Adam(model.parameters(), lr=lr, weight_decay=1e-4)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
        optimizer, T_max=epochs, eta_min=1e-5)

    loss_keys = ['total', 'recon', 'kl', 'phys', 'passiv']
    history   = {f'train_{k}': [] for k in loss_keys}
    history.update({'val_total'     : [],
                    'val_smape_obs' : [],   # 5-param SMAPE (used for checkpointing)
                    'val_smape_all' : [],   # 6-param SMAPE (diagnostic only)
                    'sigma_ld'      : [],
                    'sigma_obs_mean': []})

    best_val_smape = float('inf')
    best_state     = None
    best_epoch     = -1

    for epoch in range(1, epochs + 1):
        # ── Train ─────────────────────────────────────────────────────────
        model.train()
        accum  = {k: 0.0 for k in loss_keys}
        n_seen = 0

        for x_b, y_b in train_loader:
            x_b, y_b = x_b.to(device), y_b.to(device)
            optimizer.zero_grad()
            z_recon, mu, logvar, X_dec, _ = model(x_b)
            L_total, comp = cvae_loss(z_recon, x_b, mu, logvar, y_b, X_dec, epoch, pw)
            L_total.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
            optimizer.step()
            bs = len(x_b)
            for k in loss_keys: accum[k] += comp[f'L_{k}'] * bs
            n_seen += bs

        for k in loss_keys:
            accum[k] /= n_seen
            history[f'train_{k}'].append(accum[k])

        # ── Validation ────────────────────────────────────────────────────
        model.eval()
        val_total_acc  = 0.0
        smape_obs_acc  = smape_all_acc  = 0.0
        sigma_ld_acc   = sigma_obs_acc  = 0.0
        val_seen       = 0

        with torch.no_grad():
            for x_b, y_b in val_loader:
                x_b, y_b = x_b.to(device), y_b.to(device)
                z_recon, mu, logvar, X_dec, _ = model(x_b)

                L_total, _ = cvae_loss(z_recon, x_b, mu, logvar, y_b, X_dec, epoch, pw)
                val_total_acc += L_total.item() * len(x_b)

                sigma = torch.exp(0.5 * logvar)
                sigma_ld_acc  += sigma[:, LDV_IDX].mean().item() * len(x_b)
                sigma_obs_acc += sigma[:, OBS_IDX].mean().item() * len(x_b)

                y_pred_p = inverse_transform_targets(mu.cpu().numpy())
                y_true_p = inverse_transform_targets(y_b.cpu().numpy())

                smape_obs_acc += _smape_obs(y_pred_p, y_true_p) * len(x_b)
                smape_all_acc += np.mean(200.0 * np.abs(y_pred_p - y_true_p) /
                                         (np.abs(y_true_p) + np.abs(y_pred_p) + 1e-8)) * len(x_b)
                val_seen += len(x_b)

        val_smape_obs  = smape_obs_acc  / val_seen
        val_smape_all  = smape_all_acc  / val_seen
        s_ld           = sigma_ld_acc   / val_seen
        s_obs          = sigma_obs_acc  / val_seen

        history['val_total'].append(val_total_acc  / val_seen)
        history['val_smape_obs'].append(val_smape_obs)
        history['val_smape_all'].append(val_smape_all)
        history['sigma_ld'].append(s_ld)
        history['sigma_obs_mean'].append(s_obs)
        scheduler.step()

        # ── Checkpoint on 5-param SMAPE (Ldv excluded) ────────────────────
        if val_smape_obs < best_val_smape:
            best_val_smape = val_smape_obs
            best_state     = {k: v.cpu().clone() for k, v in model.state_dict().items()}
            best_epoch     = epoch

        if epoch % 20 == 0 or epoch == 1:
            ratio = s_ld / (s_obs + 1e-8)
            print(f"Ep {epoch:>3d} | "
                  f"Lrec={accum['recon']:.5f} | "
                  f"LKL={accum['kl']:.5f} | "
                  f"Lphy={accum['phys']:.5f} | "
                  f"Lpas={accum['passiv']:.2e} || "
                  f"SMAPE(obs)={val_smape_obs:.3f}%  "
                  f"SMAPE(all)={val_smape_all:.3f}%  "
                  f"σ_Ld/σ_obs={ratio:.2f}×")

    model.load_state_dict(best_state)
    print(f"\n✅ Best weights restored (val_SMAPE_obs={best_val_smape:.4f}% "
          f"@ epoch {best_epoch}/{epochs})")
    return model, history, best_epoch


# ─────────────────────────────────────────────────────────────────────────────
# § 7  Evaluation & Diagnostics
# ─────────────────────────────────────────────────────────────────────────────

def evaluate_cvae(model, loader, split_name='Test'):
    model.eval()
    mu_list, y_list = [], []
    with torch.no_grad():
        for x_b, y_b in loader:
            _, mu, _, _, _ = model(x_b.to(device))
            mu_list.append(mu.cpu().numpy())
            y_list.append(y_b.numpy())

    y_pred = inverse_transform_targets(np.concatenate(mu_list))
    y_true = inverse_transform_targets(np.concatenate(y_list))

    print(f"\n── Per-parameter Metrics [{split_name}] ──────────────────────────")
    smapes, r2s = {}, {}
    for k, name in enumerate(TARGET_COLS):
        t, p  = y_true[:, k], y_pred[:, k]
        r2    = r2_score(t, p)
        smape = np.mean(200.0 * np.abs(t - p) / (np.abs(t) + np.abs(p) + 1e-8))
        smapes[name], r2s[name] = smape, r2
        flag  = " [null-space — poor R² expected]" if name == 'Ldv' else ""
        qual  = ("✅ Excellent" if r2 >= 0.95 else "✅ Good" if r2 >= 0.90
                 else "⚠️ Moderate" if r2 >= 0.70 else "❌ Poor")
        print(f"  {name:>6s}  R²={r2:>8.4f}  SMAPE={smape:>7.3f}%  {qual}{flag}")

    obs_r2    = np.mean([r2s[TARGET_COLS[i]]    for i in OBS_IDX])
    obs_smape = np.mean([smapes[TARGET_COLS[i]] for i in OBS_IDX])
    print(f"\n  Mean (5 observable):  R²={obs_r2:.4f}  SMAPE={obs_smape:.3f}%")
    print(f"  Mean (all 6):         R²={np.mean(list(r2s.values())):.4f}  "
          f"SMAPE={np.mean(list(smapes.values())):.3f}%")
    return smapes, r2s


def ld_unobservability_report(model, loader):
    """
    The definitive null-space diagnostic for Architecture Idea 2.
    Expected outcome after stop-gradient fix:
      σ_Ld ≈ 1.0 (KL equilibrium, no reconstruction pressure)
      σ_obs < 1.0 (reconstruction pressure pushes these down)
      Ratio >> 1.5
    """
    model.eval()
    sigma_all = []
    with torch.no_grad():
        for x_b, _ in loader:
            _, _, logvar, _, _ = model(x_b.to(device))
            sigma_all.append(torch.exp(0.5 * logvar).cpu().numpy())
    sigma_all  = np.concatenate(sigma_all)
    mean_sigma = sigma_all.mean(axis=0)

    mean_sigma_obs = mean_sigma[OBS_IDX].mean()
    ratio          = mean_sigma[LDV_IDX] / (mean_sigma_obs + 1e-8)

    print("\n── Posterior σ per Parameter (Ld Unobservability Diagnostic) ─────")
    print(f"  {'Param':>6s}  {'Mean σ':>10s}  {'Min σ':>10s}  {'Max σ':>10s}  {'Governed by':>15s}")
    for i, name in enumerate(TARGET_COLS):
        gov    = "KL + stop-grad" if i == LDV_IDX else "KL + Lrecon"
        marker = " ◄" if i == LDV_IDX else ""
        print(f"  {name:>6s}  {mean_sigma[i]:>10.4f}  "
              f"{sigma_all[:,i].min():>10.4f}  "
              f"{sigma_all[:,i].max():>10.4f}  "
              f"{gov:>15s}{marker}")

    print(f"\n  σ_Ldv         = {mean_sigma[LDV_IDX]:.4f}")
    print(f"  σ̄_observable  = {mean_sigma_obs:.4f}")
    print(f"  Ratio         = {ratio:.2f}×")

    if ratio > 2.5:
        print("  ✅ NULL SPACE STRONGLY CONFIRMED — posterior correctly uninformed about Ld.")
    elif ratio > 1.5:
        print("  ✅ NULL SPACE CONFIRMED.")
    else:
        print("  ⚠️  Ratio < 1.5 — stop-gradient may not have taken effect or β too low.")
    return sigma_all


def bottleneck_distribution_report(model, loader):
    model.eval()
    mu_all = []
    with torch.no_grad():
        for x_b, _ in loader:
            _, mu, _, _, _ = model(x_b.to(device))
            mu_all.append(mu.cpu().numpy())
    mu_all = np.concatenate(mu_all)
    print("\n── Posterior Mean (μ) Saturation Diagnostic ─────────────────────")
    print(f"  {'Param':>6s}  {'min':>8s}  {'max':>8s}  {'mean':>8s}  "
          f"{'<-3σ (%)':>10s}  {'>+3σ (%)':>10s}  Risk")
    for i, name in enumerate(TARGET_COLS):
        col  = mu_all[:, i]
        lo   = (col < -3.0).mean() * 100
        hi   = (col >  3.0).mean() * 100
        risk = "⚠️  HIGH" if (lo > 5 or hi > 5) else "✅  OK"
        print(f"  {name:>6s}  {col.min():>8.4f}  {col.max():>8.4f}  "
              f"{col.mean():>8.4f}  {lo:>10.2f}  {hi:>10.2f}  {risk}")


def passivity_report(model, loader):
    model.eval()
    total_p = n = 0
    with torch.no_grad():
        for x_b, _ in loader:
            _, _, _, X_dec, _ = model(x_b.to(device))
            total_p += passivity_loss(X_dec).item() * len(x_b)
            n       += len(x_b)
    mean_p = total_p / n
    print(f"\nPassivity Report (test set):")
    print(f"  Mean strict passivity violation: {mean_p:.4e}  [expected ~0]")
    return mean_p


def posterior_uncertainty_plot(model, loader, save_path=None):
    model.eval()
    sigma_all = []
    with torch.no_grad():
        for x_b, _ in loader:
            _, _, logvar, _, _ = model(x_b.to(device))
            sigma_all.append(torch.exp(0.5 * logvar).cpu().numpy())
    sigma_all      = np.concatenate(sigma_all)
    mean_sigma_obs = sigma_all[:, OBS_IDX].mean()

    fig, axes = plt.subplots(1, 2, figsize=(14, 5))

    ax = axes[0]
    parts = ax.violinplot([sigma_all[:, i] for i in range(DIM_PHYS)],
                          positions=range(DIM_PHYS), showmeans=True, showmedians=True)
    for i, body in enumerate(parts['bodies']):
        body.set_facecolor('#d65f5f' if i == LDV_IDX else '#4878d0')
        body.set_alpha(0.65)
    ax.axhline(mean_sigma_obs, color='gray', linestyle='--', lw=1.2,
               label=f'Mean σ (observable) = {mean_sigma_obs:.3f}')
    ax.axhline(1.0, color='green', linestyle=':', lw=1.0, label='KL equilibrium (σ=1)')
    ax.set_xticks(range(DIM_PHYS)); ax.set_xticklabels(TARGET_COLS, fontsize=11)
    ax.set_ylabel('Posterior σ', fontsize=11)
    ax.set_title('Posterior Uncertainty per Parameter\n'
                 'Red=Ldv should cluster near σ=1.0 (KL only)\n'
                 'Blue should be <1.0 (reconstruction pressure)', fontsize=9)
    ax.legend(fontsize=8)

    ax2 = axes[1]
    n_show = min(1000, len(sigma_all))
    idx    = np.random.choice(len(sigma_all), n_show, replace=False)
    ratio  = sigma_all[idx, LDV_IDX] / (sigma_all[idx][:, OBS_IDX].mean(axis=1) + 1e-8)
    ax2.hist(ratio, bins=50, color='#d65f5f', alpha=0.7, edgecolor='white')
    ax2.axvline(1.0, color='k', linestyle='--', lw=1.2, label='ratio = 1 (baseline)')
    ax2.axvline(ratio.mean(), color='red', linestyle='-', lw=1.5,
                label=f'mean ratio = {ratio.mean():.2f}×')
    ax2.set_xlabel('σ_Ldv / σ̄_others  (per sample)', fontsize=11)
    ax2.set_ylabel('Count', fontsize=11)
    ax2.set_title('Ldv Uncertainty Ratio\n(>> 1 confirms unobservability)', fontsize=10)
    ax2.legend(fontsize=9)
    plt.tight_layout()
    if save_path: plt.savefig(save_path, dpi=150, bbox_inches='tight')
    plt.show()


def plot_training_curves(history, save_path=None):
    fig, axes = plt.subplots(1, 5, figsize=(28, 4))
    ep = range(1, len(history['train_total']) + 1)

    colours = {'recon':'steelblue','kl':'darkorange','phys':'green','passiv':'crimson'}
    for k, c in colours.items():
        axes[0].plot(ep, history[f'train_{k}'], label=f'L_{k}', color=c, lw=0.9)
    axes[0].set_yscale('log'); axes[0].set_title('Loss Components (log scale)')
    axes[0].legend(fontsize=8); axes[0].set_xlabel('Epoch')

    axes[1].plot(ep, history['train_total'], label='Train'); axes[1].plot(ep, history['val_total'], label='Val', ls='--')
    axes[1].set_title('Total Loss'); axes[1].legend(); axes[1].set_xlabel('Epoch')

    axes[2].plot(ep, history['val_smape_obs'], color='purple', label='5-param (obs)')
    axes[2].plot(ep, history['val_smape_all'], color='gray',   label='6-param (all)', ls='--')
    axes[2].set_title('Val SMAPE (%) — checkpoint on obs only'); axes[2].legend(fontsize=8)
    axes[2].set_xlabel('Epoch')

    axes[3].plot(ep, history['train_kl'], color='darkorange')
    axes[3].set_title('KL Divergence (train)'); axes[3].set_xlabel('Epoch')

    # The key plot — σ_Ld should rise above σ_obs after the stop-gradient fix
    axes[4].plot(ep, history['sigma_ld'],       color='#d65f5f', lw=1.5, label='σ_Ldv')
    axes[4].plot(ep, history['sigma_obs_mean'], color='#4878d0', lw=1.5, label='σ̄_observable')
    axes[4].axhline(1.0, color='green', linestyle=':', lw=1.0, label='KL equil. (σ=1)')
    axes[4].set_title('σ over Training\n(σ_Ld should separate above σ_obs)')
    axes[4].legend(fontsize=8); axes[4].set_xlabel('Epoch')

    plt.tight_layout()
    if save_path: plt.savefig(save_path, dpi=150, bbox_inches='tight')
    plt.show()


def decoder_validation_plot(model, loader, n_samples=3, save_path=None):
    model.eval()
    with torch.no_grad():
        x_b, _ = next(iter(loader))
        _, _, _, X_dec, X_true = model(x_b[:n_samples].to(device))
    Xd, Xt = X_dec.cpu().numpy(), X_true.cpu().numpy()
    fq     = np.linspace(0.04, 43.5, NF)
    panels = [('S11 Re', slice(None, NF)),       ('S11 Im', slice(NF, 2*NF)),
              ('S21 Re', slice(2*NF, 3*NF)),     ('S21 Im', slice(3*NF, 4*NF)),
              ('S22 Re', slice(4*NF, 5*NF)),     ('S22 Im', slice(5*NF, None))]
    fig, axes = plt.subplots(n_samples, 6, figsize=(26, 3.5*n_samples))
    for row in range(n_samples):
        for col, (title, sl) in enumerate(panels):
            ax = axes[row, col]
            ax.plot(fq, Xt[row, sl], 'k-',  lw=1.5, label='True')
            ax.plot(fq, Xd[row, sl], 'r--', lw=1.0, label='CVAE')
            mse = np.mean((Xt[row, sl] - Xd[row, sl])**2)
            ax.set_title(f'S{row+1} — {title}\nMSE={mse:.2e}', fontsize=7)
            ax.set_xlabel('Freq (GHz)', fontsize=7); ax.tick_params(labelsize=6)
            if col == 0: ax.set_ylabel('S-param', fontsize=7)
            if row == 0 and col == 0: ax.legend(fontsize=6)
    plt.suptitle('CVAE v5 Decoder Reconstruction', fontsize=10)
    plt.tight_layout()
    if save_path: plt.savefig(save_path, dpi=150, bbox_inches='tight')
    plt.show()


# ─────────────────────────────────────────────────────────────────────────────
# § 8  Load PCA bridge & instantiate model
# ─────────────────────────────────────────────────────────────────────────────

V_pca_np        = np.load("V_pca_bridge.npy").astype(np.float32)
mu_pca_np       = np.load("mu_scaler_bridge.npy").astype(np.float32)
feature_std_np  = np.load("std_scaler_bridge.npy").astype(np.float32)
feature_mean_np = np.load("scaler_mean_bridge.npy").astype(np.float32)
_sp             = np.load("pca_score_scaler_params.npz")
score_mean_np   = _sp['score_mean'].astype(np.float32)
score_std_np    = _sp['score_std'].astype(np.float32)

V_pca_t        = torch.tensor(V_pca_np,        dtype=torch.float32)
mu_pca_t       = torch.tensor(mu_pca_np,       dtype=torch.float32)
score_mean_t   = torch.tensor(score_mean_np,   dtype=torch.float32)
score_std_t    = torch.tensor(score_std_np,    dtype=torch.float32)
feature_mean_t = torch.tensor(feature_mean_np, dtype=torch.float32)
feature_std_t  = torch.tensor(feature_std_np,  dtype=torch.float32)

print(f"\n── CVAE v5 Configuration ────────────────────────────────────────────")
print(f"  Device              : {device}")
print(f"  DIM_PCA             : {DIM_PCA}")
print(f"  DIM_PHYS (latent)   : {DIM_PHYS}  (Ldv retained — UQ via stop-grad)")
print(f"  BETA_KL             : {BETA_KL}   (β for observable dims)")
print(f"  BETA_LDV_MULT       : {BETA_LDV_MULT}×  (β_Ld = {BETA_KL * BETA_LDV_MULT})")
print(f"  LAMBDA1 (phys)      : {LAMBDA1}")
print(f"  LAMBDA_PASSIV       : {LAMBDA_PASSIV}   (reduced from 500; data already passive)")
print(f"  FREE_BITS           : {FREE_BITS} nats/dim  (prevents σ_obs collapse)")
print(f"  PHYS_WEIGHTS        : {PHYS_WEIGHTS}  (Ldv=0.0)")
print(f"  Checkpoint metric   : val_SMAPE_obs (5 observable params only)")
print(f"  N_train/val/test    : {len(train_idx_np)} / {len(val_idx_np)} / {len(test_idx_np)}")
print(f"\n  KEY FIX: z_Ld is detached before entering decoder → "
      f"∂L_recon/∂σ_Ld = 0")
print(f"  Expected: σ_Ld → ~1.0,  σ_obs < 1.0,  ratio > 2×")


# ─────────────────────────────────────────────────────────────────────────────
# § 9  Train
# ─────────────────────────────────────────────────────────────────────────────

print("\n── Training CVAE v5 (seed=42) ──────────────────────────────────────")
model_cvae = PhysicsSupervisedCVAE(
    V_pca_t, mu_pca_t, score_mean_t, score_std_t,
    feature_mean_t, feature_std_t
).to(device)

model_cvae, history, best_ep = train_cvae(
    model_cvae, train_loader, val_loader,
    epochs=500, lr=1e-3, seed=42)


# ─────────────────────────────────────────────────────────────────────────────
# § 10  Evaluation & Diagnostics
# ─────────────────────────────────────────────────────────────────────────────

plot_training_curves(history, save_path="cvae_v5_training_curves.png")
smapes, r2s = evaluate_cvae(model_cvae, test_loader, split_name='Test')
sigma_data  = ld_unobservability_report(model_cvae, test_loader)
bottleneck_distribution_report(model_cvae, test_loader)
decoder_validation_plot(model_cvae, test_loader, n_samples=3,
                        save_path="cvae_v5_decoder_validation.png")
posterior_uncertainty_plot(model_cvae, test_loader,
                           save_path="cvae_v5_posterior_uncertainty.png")
passivity_report(model_cvae, test_loader)


# ─────────────────────────────────────────────────────────────────────────────
# § 11  Save checkpoint
# ─────────────────────────────────────────────────────────────────────────────

torch.save({
    'model_state_dict'  : model_cvae.state_dict(),
    'y_scalers'         : y_scalers,
    'log_targets'       : LOG_TARGETS,
    'target_cols'       : TARGET_COLS,
    'best_epoch'        : best_ep,
    'total_epochs'      : 500,
    'history'           : history,
    'dim_pca'           : DIM_PCA,
    'dim_phys'          : DIM_PHYS,
    'beta_kl'           : BETA_KL,
    'beta_ldv_mult'     : BETA_LDV_MULT,
    'lambda1'           : LAMBDA1,
    'lambda_passiv'     : LAMBDA_PASSIV,
    'free_bits'         : FREE_BITS,
    'phys_weights'      : PHYS_WEIGHTS,
    'architecture'      : 'Physics-Supervised CVAE v5 — stop-grad Ld fix',
    'change_log'        : ['stop-grad z_Ld in decoder',
                           'per-dim KL weights (Ld × 10)',
                           'free-bits on observable dims',
                           'lambda_passiv=5 (was 500)',
                           'checkpoint on 5-param SMAPE'],
}, "cvae_v5_physics_supervised_final.pt")

print(f"\n✅ CVAE v5 checkpoint → cvae_v5_physics_supervised_final.pt  "
      f"(best epoch {best_ep}/500)")

# ╔══════════════════════════════════════════════════════════════════════════╗
# ║  CELL 4 — Unified Model Comparison: PIAE (Idea 1) vs CVAE (Idea 2)       ║
# ║                                                                           ║
# ║  Evaluation philosophy:                                                   ║
# ║  • Both models evaluated on the IDENTICAL held-out test set               ║
# ║  • IDENTICAL metric (MAPE) on IDENTICAL parameter set (5 observable)      ║
# ║  • Ldv is reported separately as a UQ diagnostic for CVAE only            ║
# ║  • SMAPE is NOT used — it is numerically incompatible with MAPE           ║
# ║                                                                           ║
# ║  Why MAPE not SMAPE:                                                      ║
# ║    MAPE  = |y_true - y_pred| / |y_true|                                  ║
# ║    SMAPE = 2|y_true - y_pred| / (|y_true| + |y_pred|)                    ║
# ║    These produce DIFFERENT numbers on identical predictions.               ║
# ║    A PIAE MAPE of 2.6% vs CVAE SMAPE of 1.8% is an invalid comparison.  ║
# ║    Since PIAE used MAPE, CVAE must also use MAPE for a fair table.        ║
# ║    Ldv MAPE is reported but excluded from model selection and means.      ║
# ╚══════════════════════════════════════════════════════════════════════════╝

import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score
import math, warnings
warnings.filterwarnings("ignore")

torch.manual_seed(42)
np.random.seed(42)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# ─────────────────────────────────────────────────────────────────────────────
# § 0  Shared constants (must match Cell 1 / Cell 2 / Cell 3)
# ─────────────────────────────────────────────────────────────────────────────
NF      = 435
DIM_RAW = 2610

_sp      = np.load("pca_score_scaler_params.npz")
DIM_PCA  = int(_sp['n_components'])   # 10

# PIAE targets (5 params — Ld excluded)
PIAE_TARGET_COLS = ['Rbv', 'Cbv', 'Rdv', 'Cdv', 'Rav']

# CVAE targets (6 params — Ld retained for UQ)
CVAE_TARGET_COLS = ['Rbv', 'Cbv', 'Rdv', 'Ldv', 'Cdv', 'Rav']

# The 5 observable params used for ALL cross-model comparisons
OBS_COLS = ['Rbv', 'Cbv', 'Rdv', 'Cdv', 'Rav']
LDV_IDX_CVAE = CVAE_TARGET_COLS.index('Ldv')   # = 3
OBS_IDX_CVAE = [i for i in range(6) if i != LDV_IDX_CVAE]

PCA_COLS = [f'PC{i+1}' for i in range(DIM_PCA)]

# ─────────────────────────────────────────────────────────────────────────────
# § 1  Rebuild scalers from saved indices (same logic as Cell 2 / Cell 3)
# ─────────────────────────────────────────────────────────────────────────────
df_pca       = pd.read_csv("ssec_pca_final_v2.csv")
train_idx_np = np.load("split_train_idx.npy")
val_idx_np   = np.load("split_val_idx.npy")
test_idx_np  = np.load("split_test_idx.npy")

X_np = df_pca[PCA_COLS].values.astype(np.float32)

def _build_scalers(target_cols):
    """Reconstruct y_scalers for a given target list."""
    Y_raw  = df_pca[target_cols].values.astype(np.float64)
    Y_proc = Y_raw.copy()
    for i in range(len(target_cols)):
        Y_proc[:, i] = np.log10(np.abs(Y_proc[:, i]) + 1e-30)
    scalers  = {}
    Y_scaled = np.zeros_like(Y_proc, dtype=np.float32)
    for i, t in enumerate(target_cols):
        sc = StandardScaler()
        sc.fit(Y_proc[train_idx_np, i:i+1])
        Y_scaled[:, i] = sc.transform(Y_proc[:, i:i+1]).ravel()
        scalers[t] = sc
    return scalers, Y_scaled

piae_scalers, _  = _build_scalers(PIAE_TARGET_COLS)
cvae_scalers, _  = _build_scalers(CVAE_TARGET_COLS)

def _inverse(Y_sc, target_cols, scalers):
    Y_out = np.zeros_like(Y_sc, dtype=np.float64)
    for i, t in enumerate(target_cols):
        Y_out[:, i] = scalers[t].inverse_transform(Y_sc[:, i:i+1]).ravel()
        Y_out[:, i] = 10.0 ** Y_out[:, i]
    return Y_out

# ─────────────────────────────────────────────────────────────────────────────
# § 2  Rebuild PIAE architecture (must match Cell 2 exactly)
# ─────────────────────────────────────────────────────────────────────────────
DIM_PHYS_PIAE = 5   # Ld excluded

class PIAEEncoder(nn.Module):
    def __init__(self, input_dim=DIM_PCA, output_dim=DIM_PHYS_PIAE,
                 hidden_dims=(128, 256, 128)):
        super().__init__()
        layers, d = [], input_dim
        for h in hidden_dims:
            layers += [nn.Linear(d, h), nn.LayerNorm(h), nn.ReLU()]
            d = h
        layers.append(nn.Linear(d, output_dim))
        self.net = nn.Sequential(*layers)
    def forward(self, x): return self.net(x)

class PIAEDecoder(nn.Module):
    def __init__(self, input_dim=DIM_PHYS_PIAE, output_dim=DIM_PCA,
                 hidden_dims=(128, 256, 128)):
        super().__init__()
        layers, d = [], input_dim
        for h in hidden_dims:
            layers += [nn.Linear(d, h), nn.ReLU()]
            d = h
        layers.append(nn.Linear(d, output_dim))
        self.net = nn.Sequential(*layers)
    def forward(self, y): return self.net(y)

class PIAE(nn.Module):
    def __init__(self, V_pca, mu_pca, score_mean, score_std, feature_mean, feature_std):
        super().__init__()
        self.encoder     = PIAEEncoder()
        self.decoder     = PIAEDecoder()
        self.residual_net = nn.Sequential(
            nn.Linear(DIM_RAW, 512), nn.ReLU(), nn.Linear(512, DIM_RAW))
        nn.init.zeros_(self.residual_net[-1].weight)
        nn.init.zeros_(self.residual_net[-1].bias)
        self.register_buffer('V_pca',        V_pca)
        self.register_buffer('mu_pca',       mu_pca)
        self.register_buffer('score_mean',   score_mean)
        self.register_buffer('score_std',    score_std)
        self.register_buffer('feature_mean', feature_mean)
        self.register_buffer('feature_std',  feature_std)

    def pca_invert(self, z_norm):
        z_unnorm = z_norm * self.score_std + self.score_mean
        X_std    = z_unnorm @ self.V_pca.T + self.mu_pca
        return X_std * self.feature_std + self.feature_mean

    def forward(self, x_pca):
        y_bott          = self.encoder(x_pca)
        z_recon         = self.decoder(y_bott)
        X_pca_only      = self.pca_invert(z_recon)
        X_2610_true     = self.pca_invert(x_pca)
        X_2610_decoded  = X_pca_only + 0.01 * self.residual_net(X_pca_only)
        return z_recon, y_bott, X_2610_decoded, X_2610_true


# ─────────────────────────────────────────────────────────────────────────────
# § 3  Rebuild CVAE architecture (must match Cell 3 v5 exactly)
# ─────────────────────────────────────────────────────────────────────────────
DIM_PHYS_CVAE = 6
LDV_IDX       = 3

class CVAEEncoder(nn.Module):
    def __init__(self, input_dim=DIM_PCA, latent_dim=DIM_PHYS_CVAE,
                 hidden_dims=(128, 256, 256, 128)):
        super().__init__()
        layers, d = [], input_dim
        for h in hidden_dims:
            layers += [nn.Linear(d, h), nn.LayerNorm(h), nn.GELU()]
            d = h
        self.shared    = nn.Sequential(*layers)
        self.fc_mu     = nn.Linear(d, latent_dim)
        self.fc_logvar = nn.Linear(d, latent_dim)
    def forward(self, x):
        h = self.shared(x)
        return self.fc_mu(h), torch.clamp(self.fc_logvar(h), -10.0, 4.0)

class CVAEDecoder(nn.Module):
    def __init__(self, latent_dim=DIM_PHYS_CVAE, output_dim=DIM_PCA,
                 hidden_dims=(128, 256, 256, 128)):
        super().__init__()
        layers, d = [], latent_dim
        for h in hidden_dims:
            layers += [nn.Linear(d, h), nn.GELU()]
            d = h
        layers.append(nn.Linear(d, output_dim))
        self.net = nn.Sequential(*layers)
    def forward(self, z): return self.net(z)

class PhysicsSupervisedCVAE(nn.Module):
    def __init__(self, V_pca, mu_pca, score_mean, score_std, feature_mean, feature_std):
        super().__init__()
        self.encoder = CVAEEncoder()
        self.decoder = CVAEDecoder()
        self.register_buffer('V_pca',        V_pca)
        self.register_buffer('mu_pca',       mu_pca)
        self.register_buffer('score_mean',   score_mean)
        self.register_buffer('score_std',    score_std)
        self.register_buffer('feature_mean', feature_mean)
        self.register_buffer('feature_std',  feature_std)

    def pca_invert(self, z_norm):
        z_unnorm = z_norm * self.score_std + self.score_mean
        X_std    = z_unnorm @ self.V_pca.T + self.mu_pca
        return X_std * self.feature_std + self.feature_mean

    def forward(self, x_pca):
        mu, logvar = self.encoder(x_pca)
        z          = mu + torch.exp(0.5 * logvar) * torch.randn_like(mu)
        z_dec      = torch.cat([z[:, :LDV_IDX],
                                z[:, LDV_IDX:LDV_IDX+1].detach(),
                                z[:, LDV_IDX+1:]], dim=1)
        z_recon        = self.decoder(z_dec)
        X_2610_decoded = self.pca_invert(z_recon)
        X_2610_true    = self.pca_invert(x_pca)
        return z_recon, mu, logvar, X_2610_decoded, X_2610_true


# ─────────────────────────────────────────────────────────────────────────────
# § 4  Load PCA bridge matrices & checkpoints
# ─────────────────────────────────────────────────────────────────────────────
V_pca_np        = np.load("V_pca_bridge.npy").astype(np.float32)
mu_pca_np       = np.load("mu_scaler_bridge.npy").astype(np.float32)
feature_std_np  = np.load("std_scaler_bridge.npy").astype(np.float32)
feature_mean_np = np.load("scaler_mean_bridge.npy").astype(np.float32)
score_mean_np   = _sp['score_mean'].astype(np.float32)
score_std_np    = _sp['score_std'].astype(np.float32)

def _buffers():
    return (torch.tensor(V_pca_np),        torch.tensor(mu_pca_np),
            torch.tensor(score_mean_np),   torch.tensor(score_std_np),
            torch.tensor(feature_mean_np), torch.tensor(feature_std_np))

# ── Load PIAE ─────────────────────────────────────────────────────────────
piae_model = PIAE(*_buffers()).to(device)
# piae_ckpt  = torch.load("piae_v3_s21_final.pt", map_location=device)
piae_ckpt = torch.load("piae_v3_s21_final.pt", map_location=device, weights_only=False)
piae_model.load_state_dict(piae_ckpt['model_state_dict'])
piae_model.eval()
print("✅ PIAE checkpoint loaded")

# ── Load CVAE ─────────────────────────────────────────────────────────────
cvae_model = PhysicsSupervisedCVAE(*_buffers()).to(device)
# cvae_ckpt  = torch.load("cvae_v5_physics_supervised_final.pt", map_location=device)
cvae_ckpt = torch.load("cvae_v5_physics_supervised_final.pt", map_location=device, weights_only=False)
cvae_model.load_state_dict(cvae_ckpt['model_state_dict'])
cvae_model.eval()
print("✅ CVAE v5 checkpoint loaded")

# ─────────────────────────────────────────────────────────────────────────────
# § 5  Shared DataLoader (test set only)
# ─────────────────────────────────────────────────────────────────────────────

# We need Y_scaled for the test loader — build from CVAE (6-param) targets
_, Y_scaled_cvae = _build_scalers(CVAE_TARGET_COLS)

from torch.utils.data import Dataset, DataLoader, Subset

class SSECDataset(Dataset):
    def __init__(self, X, Y):
        self.X = torch.tensor(X, dtype=torch.float32)
        self.Y = torch.tensor(Y, dtype=torch.float32)
    def __len__(self):        return len(self.X)
    def __getitem__(self, i): return self.X[i], self.Y[i]

test_dataset = SSECDataset(X_np, Y_scaled_cvae)
test_set     = Subset(test_dataset, test_idx_np.tolist())
test_loader  = DataLoader(test_set, batch_size=512, shuffle=False,
                          pin_memory=True, num_workers=2, persistent_workers=True)

# ─────────────────────────────────────────────────────────────────────────────
# § 6  Inference on test set
# ─────────────────────────────────────────────────────────────────────────────

def run_piae_inference(model, loader):
    """Returns predictions and ground truth for all 5 PIAE observable params."""
    pred_list, true_list = [], []
    with torch.no_grad():
        for x_b, y_b in loader:
            _, y_bott, _, _ = model(x_b.to(device))
            pred_list.append(y_bott.cpu().numpy())
            # y_b has 6 cols (CVAE ordering) — remap to 5-param PIAE ordering
            true_list.append(y_b.cpu().numpy())

    # y_b is in CVAE 6-param scaled space; extract & invert only obs params
    pred_scaled  = np.concatenate(pred_list)           # (N, 5) already PIAE output
    true_scaled6 = np.concatenate(true_list)           # (N, 6) CVAE ordering

    # Invert PIAE predictions using PIAE scalers
    pred_phys = _inverse(pred_scaled, PIAE_TARGET_COLS, piae_scalers)

    # Invert ground truth using CVAE scalers, then pick observable cols
    true_phys6 = _inverse(true_scaled6, CVAE_TARGET_COLS, cvae_scalers)
    # OBS_COLS order in CVAE: Rbv=0, Cbv=1, Rdv=2, Cdv=4, Rav=5
    cvae_obs_idx = [CVAE_TARGET_COLS.index(c) for c in OBS_COLS]
    true_phys5   = true_phys6[:, cvae_obs_idx]         # (N, 5) same order as OBS_COLS

    return pred_phys, true_phys5


def run_cvae_inference(model, loader):
    """Returns μ (point estimate) and σ (uncertainty) for all 6 CVAE params."""
    mu_list, sigma_list, true_list = [], [], []
    with torch.no_grad():
        for x_b, y_b in loader:
            _, mu, logvar, _, _ = model(x_b.to(device))
            mu_list.append(mu.cpu().numpy())
            sigma_list.append(torch.exp(0.5 * logvar).cpu().numpy())
            true_list.append(y_b.cpu().numpy())

    mu_scaled    = np.concatenate(mu_list)
    sigma_all    = np.concatenate(sigma_list)
    true_scaled6 = np.concatenate(true_list)

    pred_phys6 = _inverse(mu_scaled,    CVAE_TARGET_COLS, cvae_scalers)
    true_phys6 = _inverse(true_scaled6, CVAE_TARGET_COLS, cvae_scalers)
    return pred_phys6, true_phys6, sigma_all


print("\nRunning inference on test set...")
piae_pred, piae_true      = run_piae_inference(piae_model, test_loader)
cvae_pred6, cvae_true6, cvae_sigma = run_cvae_inference(cvae_model, test_loader)

# Extract 5-param slices from CVAE for fair comparison
cvae_obs_idx = [CVAE_TARGET_COLS.index(c) for c in OBS_COLS]
cvae_pred5   = cvae_pred6[:, cvae_obs_idx]
cvae_true5   = cvae_true6[:, cvae_obs_idx]

print(f"  Test samples: {len(piae_pred)}")

# ─────────────────────────────────────────────────────────────────────────────
# § 7  Compute metrics — identical MAPE for both models on 5 observable params
# ─────────────────────────────────────────────────────────────────────────────

def compute_metrics(y_pred, y_true, param_names):
    """Compute MAPE and R² per parameter. Returns dicts."""
    mapes, r2s = {}, {}
    for k, name in enumerate(param_names):
        t, p    = y_true[:, k], y_pred[:, k]
        r2      = r2_score(t, p)
        mape    = np.mean(np.abs(t - p) / (np.abs(t) + 1e-8)) * 100.0
        mapes[name], r2s[name] = mape, r2
    return mapes, r2s


piae_mapes, piae_r2s = compute_metrics(piae_pred,  piae_true,  OBS_COLS)
cvae_mapes, cvae_r2s = compute_metrics(cvae_pred5, cvae_true5, OBS_COLS)

# Also compute Ldv metrics for CVAE (diagnostic only, not in comparison table)
ldv_pred = cvae_pred6[:, LDV_IDX_CVAE]
ldv_true = cvae_true6[:, LDV_IDX_CVAE]
ldv_r2   = r2_score(ldv_true, ldv_pred)
ldv_mape = np.mean(np.abs(ldv_pred - ldv_true) / (np.abs(ldv_true) + 1e-8)) * 100.0

# ─────────────────────────────────────────────────────────────────────────────
# § 8  Print comparison table
# ─────────────────────────────────────────────────────────────────────────────

print("\n" + "═"*78)
print("  MODEL COMPARISON TABLE — Identical metric (MAPE) on 5 observable params")
print("  Test set:  N =", len(piae_pred), "samples")
print("═"*78)
print(f"  {'Param':>6s}  │  {'PIAE (Idea 1)':^26s}  │  {'CVAE (Idea 2)':^26s}  │  {'Δ MAPE':>8s}")
print(f"  {'':>6s}  │  {'R²':>8s}  {'MAPE (%)':>8s}  {'Grade':>6s}  │  {'R²':>8s}  {'MAPE (%)':>8s}  {'Grade':>6s}  │")
print("  " + "─"*74)

def _grade(r2):
    return ("Excel." if r2 >= 0.95 else "Good" if r2 >= 0.90
            else "Mod."  if r2 >= 0.70 else "Poor")

for name in OBS_COLS:
    pr2, pm = piae_r2s[name], piae_mapes[name]
    cr2, cm = cvae_r2s[name], cvae_mapes[name]
    delta   = cm - pm   # positive = CVAE worse, negative = CVAE better
    arrow   = f"{'▲' if delta > 0 else '▼'} {abs(delta):+.3f}%"
    print(f"  {name:>6s}  │  {pr2:>8.4f}  {pm:>8.3f}%  {_grade(pr2):>6s}  │  "
          f"{cr2:>8.4f}  {cm:>8.3f}%  {_grade(cr2):>6s}  │  {arrow:>10s}")

print("  " + "─"*74)
mean_pm = np.mean([piae_mapes[n] for n in OBS_COLS])
mean_cm = np.mean([cvae_mapes[n] for n in OBS_COLS])
mean_pr = np.mean([piae_r2s[n]   for n in OBS_COLS])
mean_cr = np.mean([cvae_r2s[n]   for n in OBS_COLS])
delta_m = mean_cm - mean_pm
print(f"  {'Mean':>6s}  │  {mean_pr:>8.4f}  {mean_pm:>8.3f}%  {'':>6s}  │  "
      f"{mean_cr:>8.4f}  {mean_cm:>8.3f}%  {'':>6s}  │  "
      f"{'▲' if delta_m > 0 else '▼'} {abs(delta_m):+.3f}%")
print("═"*78)

# Ldv diagnostic (CVAE only)
print(f"\n  Ldv [NULL-SPACE — CVAE UQ diagnostic, not in comparison]")
print(f"    R²={ldv_r2:.4f}  MAPE={ldv_mape:.1f}%  "
      f"→ Poor R² confirms Ld unobservability (expected)")
print(f"    σ_Ldv = {cvae_sigma[:, LDV_IDX_CVAE].mean():.4f}  "
      f"σ̄_obs  = {cvae_sigma[:, OBS_IDX_CVAE].mean():.4f}  "
      f"Ratio = {cvae_sigma[:, LDV_IDX_CVAE].mean() / cvae_sigma[:, OBS_IDX_CVAE].mean():.2f}×")
print("═"*78)

# ─────────────────────────────────────────────────────────────────────────────
# § 9  Capability comparison (what CVAE adds beyond PIAE)
# ─────────────────────────────────────────────────────────────────────────────

print("""
  WHAT CVAE ADDS BEYOND PIAE (not reflected in MAPE/R²):
  ────────────────────────────────────────────────────────
  [1] Posterior uncertainty σ_k per parameter per sample.
      If σ_k is large for an observable param, it signals genuine
      parameter degeneracy at that specific operating point —
      a deterministic model (PIAE) would silently output a wrong value.

  [2] Ld null-space quantification.
      PIAE fixes Ld and ignores it. CVAE outputs σ_Ld >> σ_obs,
      providing a Bayesian certificate that Ld is unextractable.
      This is a rigorous finding, not an engineering workaround.

  [3] Posterior sampling → calibrated confidence intervals on
      reconstructed S-parameter spectra (PIAE gives point estimates only).

  [4] Out-of-distribution awareness.
      When an input x_pca is far from the training manifold, CVAE
      posterior widths inflate. PIAE gives an overconfident point estimate.
""")

# ─────────────────────────────────────────────────────────────────────────────
# § 10  Figure 1 — Scatter plot: predicted vs true for each observable param
#         Side-by-side PIAE (left) vs CVAE (right)
# ─────────────────────────────────────────────────────────────────────────────

fig, axes = plt.subplots(2, 5, figsize=(22, 9))
fig.suptitle('Predicted vs True — PIAE (top) vs CVAE (bottom)\n'
             'Identical test set   |   Metric: MAPE   |   5 observable params',
             fontsize=12)

colours = ['#2166ac', '#4dac26', '#d6604d', '#762a83', '#e08214']

for col, name in enumerate(OBS_COLS):
    # ── PIAE row ──────────────────────────────────────────────────────────
    ax = axes[0, col]
    pt, pp = piae_true[:, col], piae_pred[:, col]
    lim    = [min(pt.min(), pp.min()) * 0.95, max(pt.max(), pp.max()) * 1.05]
    ax.scatter(pt, pp, s=4, alpha=0.3, color=colours[col])
    ax.plot(lim, lim, 'k--', lw=1.0)
    ax.set_xlim(lim); ax.set_ylim(lim)
    ax.set_title(f'{name}\nR²={piae_r2s[name]:.4f}  MAPE={piae_mapes[name]:.2f}%',
                 fontsize=9)
    ax.set_xlabel('True', fontsize=8); ax.set_ylabel('Predicted', fontsize=8)
    ax.tick_params(labelsize=7)
    if col == 0: ax.set_ylabel('PIAE\nPredicted', fontsize=9)

    # ── CVAE row ──────────────────────────────────────────────────────────
    ax2 = axes[1, col]
    ct, cp = cvae_true5[:, col], cvae_pred5[:, col]
    lim    = [min(ct.min(), cp.min()) * 0.95, max(ct.max(), cp.max()) * 1.05]
    ax2.scatter(ct, cp, s=4, alpha=0.3, color=colours[col])
    ax2.plot(lim, lim, 'k--', lw=1.0)
    ax2.set_xlim(lim); ax2.set_ylim(lim)
    ax2.set_title(f'{name}\nR²={cvae_r2s[name]:.4f}  MAPE={cvae_mapes[name]:.2f}%',
                  fontsize=9)
    ax2.set_xlabel('True', fontsize=8); ax2.tick_params(labelsize=7)
    if col == 0: ax2.set_ylabel('CVAE\nPredicted', fontsize=9)

plt.tight_layout()
plt.savefig("comparison_scatter_piae_vs_cvae.png", dpi=150, bbox_inches='tight')
plt.show()

# ─────────────────────────────────────────────────────────────────────────────
# § 11  Figure 2 — MAPE bar chart side by side
# ─────────────────────────────────────────────────────────────────────────────

fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle('MAPE (%) Comparison — 5 Observable Parameters\n'
             '(Lower is better   |   Same metric, same test set)', fontsize=12)

x      = np.arange(len(OBS_COLS))
width  = 0.35
pm_arr = [piae_mapes[n] for n in OBS_COLS]
cm_arr = [cvae_mapes[n] for n in OBS_COLS]

# Grouped bar
ax = axes[0]
b1 = ax.bar(x - width/2, pm_arr, width, label='PIAE (Idea 1)',
            color='#4878d0', alpha=0.85, edgecolor='white')
b2 = ax.bar(x + width/2, cm_arr, width, label='CVAE (Idea 2)',
            color='#d65f5f', alpha=0.85, edgecolor='white')
ax.set_xticks(x); ax.set_xticklabels(OBS_COLS, fontsize=11)
ax.set_ylabel('MAPE (%)', fontsize=11)
ax.set_title('Per-parameter MAPE', fontsize=11)
ax.legend(fontsize=10)
ax.bar_label(b1, fmt='%.2f%%', fontsize=7, padding=2)
ax.bar_label(b2, fmt='%.2f%%', fontsize=7, padding=2)

# R² comparison
pr_arr = [piae_r2s[n] for n in OBS_COLS]
cr_arr = [cvae_r2s[n] for n in OBS_COLS]
ax2    = axes[1]
b3 = ax2.bar(x - width/2, pr_arr, width, label='PIAE (Idea 1)',
             color='#4878d0', alpha=0.85, edgecolor='white')
b4 = ax2.bar(x + width/2, cr_arr, width, label='CVAE (Idea 2)',
             color='#d65f5f', alpha=0.85, edgecolor='white')
ax2.set_xticks(x); ax2.set_xticklabels(OBS_COLS, fontsize=11)
ax2.set_ylabel('R²', fontsize=11); ax2.set_ylim(0.90, 1.002)
ax2.set_title('Per-parameter R²', fontsize=11); ax2.legend(fontsize=10)
ax2.bar_label(b3, fmt='%.4f', fontsize=7, padding=2)
ax2.bar_label(b4, fmt='%.4f', fontsize=7, padding=2)
ax2.axhline(0.95, color='gray', linestyle='--', lw=1.0, label='R²=0.95 threshold')

plt.tight_layout()
plt.savefig("comparison_metrics_bar.png", dpi=150, bbox_inches='tight')
plt.show()

# ─────────────────────────────────────────────────────────────────────────────
# § 12  Figure 3 — CVAE-exclusive: posterior σ (the UQ advantage)
# ─────────────────────────────────────────────────────────────────────────────

fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle('CVAE Exclusive Capability: Posterior Uncertainty Quantification\n'
             '(PIAE cannot produce this — it outputs point estimates only)', fontsize=11)

# Violin of σ across all 6 params
ax = axes[0]
parts = ax.violinplot([cvae_sigma[:, i] for i in range(6)],
                      positions=range(6), showmeans=True, showmedians=True)
for i, body in enumerate(parts['bodies']):
    body.set_facecolor('#d65f5f' if i == LDV_IDX_CVAE else '#4878d0')
    body.set_alpha(0.65)
ax.axhline(1.0, color='green', linestyle=':', lw=1.2, label='KL equilibrium (σ=1)')
ax.axhline(cvae_sigma[:, OBS_IDX_CVAE].mean(), color='gray', linestyle='--', lw=1.0,
           label=f'Mean σ_obs = {cvae_sigma[:, OBS_IDX_CVAE].mean():.3f}')
ax.set_xticks(range(6)); ax.set_xticklabels(CVAE_TARGET_COLS, fontsize=10)
ax.set_ylabel('Posterior σ', fontsize=11)
ax.set_title('Posterior σ Distribution\n(Red = Ldv, expected near σ=1.0)', fontsize=10)
ax.legend(fontsize=8)

# σ_Ldv vs σ_obs per sample scatter
ax2 = axes[1]
sigma_obs_per_sample = cvae_sigma[:, OBS_IDX_CVAE].mean(axis=1)
sigma_ld_per_sample  = cvae_sigma[:, LDV_IDX_CVAE]
ax2.scatter(sigma_obs_per_sample, sigma_ld_per_sample,
            s=3, alpha=0.3, color='#d65f5f')
ax2.plot([0, 2], [0, 2], 'k--', lw=1.0, label='σ_Ld = σ_obs (ratio=1)')
ratio_mean = (sigma_ld_per_sample / (sigma_obs_per_sample + 1e-8)).mean()
ax2.set_xlabel('σ̄ (observable params)', fontsize=11)
ax2.set_ylabel('σ (Ldv)', fontsize=11)
ax2.set_title(f'σ_Ldv vs σ̄_obs per test sample\nMean ratio = {ratio_mean:.2f}×  '
              f'(>1.5 confirms null space)', fontsize=10)
ax2.legend(fontsize=9)

plt.tight_layout()
plt.savefig("comparison_cvae_uq_advantage.png", dpi=150, bbox_inches='tight')
plt.show()

print("\n✅ All comparison figures saved.")
print(f"\n── Final Summary ─────────────────────────────────────────────────────")
print(f"  PIAE mean MAPE (5 params): {mean_pm:.3f}%")
print(f"  CVAE mean MAPE (5 params): {mean_cm:.3f}%")
winner = "PIAE" if mean_pm < mean_cm else "CVAE"
print(f"  Better point-estimate accuracy: {winner}")
print(f"  Uncertainty quantification:     CVAE only (PIAE cannot do this)")
print(f"  Ld null-space certificate:      CVAE only (σ ratio = {ratio_mean:.2f}×)")

